<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UbicacionesSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $ubicacion = [
      ['codigo' => 'CO-DC', 'ubicacion' => 'Distrito Capital de Bogotá'],
      ['codigo' => 'CO-DC-11001', 'ubicacion' => 'Bogotá'],
      ['codigo' => 'CO-AMA', 'ubicacion' => 'Amazonas'],
      ['codigo' => 'CO-AMA-91001', 'ubicacion' => 'Leticia'],
      ['codigo' => 'CO-AMA-91263', 'ubicacion' => 'El Encanto'],
      ['codigo' => 'CO-AMA-91405', 'ubicacion' => 'La Chorrera'],
      ['codigo' => 'CO-AMA-91407', 'ubicacion' => 'La Pedrera'],
      ['codigo' => 'CO-AMA-91430', 'ubicacion' => 'La Victoria'],
      ['codigo' => 'CO-AMA-91460', 'ubicacion' => 'Miriti - Paraná'],
      ['codigo' => 'CO-AMA-91530', 'ubicacion' => 'Puerto Alegría'],
      ['codigo' => 'CO-AMA-91536', 'ubicacion' => 'Puerto Arica'],
      ['codigo' => 'CO-AMA-91540', 'ubicacion' => 'Puerto Nariño'],
      ['codigo' => 'CO-AMA-91669', 'ubicacion' => 'Puerto Santander'],
      ['codigo' => 'CO-AMA-91798', 'ubicacion' => 'Tarapacá'],
      ['codigo' => 'CO-ANT', 'ubicacion' => 'Antioquia'],
      ['codigo' => 'CO-ANT-05001', 'ubicacion' => 'Medellín'],
      ['codigo' => 'CO-ANT-05002', 'ubicacion' => 'Abejorral'],
      ['codigo' => 'CO-ANT-05004', 'ubicacion' => 'Abriaquí'],
      ['codigo' => 'CO-ANT-05021', 'ubicacion' => 'Alejandría'],
      ['codigo' => 'CO-ANT-05030', 'ubicacion' => 'Amagá'],
      ['codigo' => 'CO-ANT-05031', 'ubicacion' => 'Amalfi'],
      ['codigo' => 'CO-ANT-05034', 'ubicacion' => 'Andes'],
      ['codigo' => 'CO-ANT-05036', 'ubicacion' => 'Angelópolis'],
      ['codigo' => 'CO-ANT-05038', 'ubicacion' => 'Angostura'],
      ['codigo' => 'CO-ANT-05040', 'ubicacion' => 'Anorí'],
      ['codigo' => 'CO-ANT-05042', 'ubicacion' => 'Santafé De Antioquia'],
      ['codigo' => 'CO-ANT-05044', 'ubicacion' => 'Anza'],
      ['codigo' => 'CO-ANT-05045', 'ubicacion' => 'Apartadó'],
      ['codigo' => 'CO-ANT-05051', 'ubicacion' => 'Arboletes'],
      ['codigo' => 'CO-ANT-05055', 'ubicacion' => 'Argelia'],
      ['codigo' => 'CO-ANT-05059', 'ubicacion' => 'Armenia'],
      ['codigo' => 'CO-ANT-05079', 'ubicacion' => 'Barbosa'],
      ['codigo' => 'CO-ANT-05086', 'ubicacion' => 'Belmira'],
      ['codigo' => 'CO-ANT-05088', 'ubicacion' => 'Bello'],
      ['codigo' => 'CO-ANT-05091', 'ubicacion' => 'Betania'],
      ['codigo' => 'CO-ANT-05093', 'ubicacion' => 'Betulia'],
      ['codigo' => 'CO-ANT-05101', 'ubicacion' => 'Ciudad Bolívar'],
      ['codigo' => 'CO-ANT-05107', 'ubicacion' => 'Briceño'],
      ['codigo' => 'CO-ANT-05113', 'ubicacion' => 'Buriticá'],
      ['codigo' => 'CO-ANT-05120', 'ubicacion' => 'Cáceres'],
      ['codigo' => 'CO-ANT-05125', 'ubicacion' => 'Caicedo'],
      ['codigo' => 'CO-ANT-05129', 'ubicacion' => 'Caldas'],
      ['codigo' => 'CO-ANT-05134', 'ubicacion' => 'Campamento'],
      ['codigo' => 'CO-ANT-05138', 'ubicacion' => 'Cañasgordas'],
      ['codigo' => 'CO-ANT-05142', 'ubicacion' => 'Caracolí'],
      ['codigo' => 'CO-ANT-05145', 'ubicacion' => 'Caramanta'],
      ['codigo' => 'CO-ANT-05147', 'ubicacion' => 'Carepa'],
      ['codigo' => 'CO-ANT-05148', 'ubicacion' => 'El Carmen De Viboral'],
      ['codigo' => 'CO-ANT-05150', 'ubicacion' => 'Carolina'],
      ['codigo' => 'CO-ANT-05154', 'ubicacion' => 'Caucasia'],
      ['codigo' => 'CO-ANT-05172', 'ubicacion' => 'Chigorodó'],
      ['codigo' => 'CO-ANT-05190', 'ubicacion' => 'Cisneros'],
      ['codigo' => 'CO-ANT-05197', 'ubicacion' => 'Cocorná'],
      ['codigo' => 'CO-ANT-05206', 'ubicacion' => 'Concepción'],
      ['codigo' => 'CO-ANT-05209', 'ubicacion' => 'Concordia'],
      ['codigo' => 'CO-ANT-05212', 'ubicacion' => 'Copacabana'],
      ['codigo' => 'CO-ANT-05234', 'ubicacion' => 'Dabeiba'],
      ['codigo' => 'CO-ANT-05237', 'ubicacion' => 'Don Matías'],
      ['codigo' => 'CO-ANT-05240', 'ubicacion' => 'Ebéjico'],
      ['codigo' => 'CO-ANT-05250', 'ubicacion' => 'El Bagre'],
      ['codigo' => 'CO-ANT-05264', 'ubicacion' => 'Entrerrios'],
      ['codigo' => 'CO-ANT-05266', 'ubicacion' => 'Envigado'],
      ['codigo' => 'CO-ANT-05282', 'ubicacion' => 'Fredonia'],
      ['codigo' => 'CO-ANT-05284', 'ubicacion' => 'Frontino'],
      ['codigo' => 'CO-ANT-05306', 'ubicacion' => 'Giraldo'],
      ['codigo' => 'CO-ANT-05308', 'ubicacion' => 'Girardota'],
      ['codigo' => 'CO-ANT-05310', 'ubicacion' => 'Gómez Plata'],
      ['codigo' => 'CO-ANT-05313', 'ubicacion' => 'Granada'],
      ['codigo' => 'CO-ANT-05315', 'ubicacion' => 'Guadalupe'],
      ['codigo' => 'CO-ANT-05318', 'ubicacion' => 'Guarne'],
      ['codigo' => 'CO-ANT-05321', 'ubicacion' => 'Guatape'],
      ['codigo' => 'CO-ANT-05347', 'ubicacion' => 'Heliconia'],
      ['codigo' => 'CO-ANT-05353', 'ubicacion' => 'Hispania'],
      ['codigo' => 'CO-ANT-05360', 'ubicacion' => 'Itagui'],
      ['codigo' => 'CO-ANT-05361', 'ubicacion' => 'Ituango'],
      ['codigo' => 'CO-ANT-05364', 'ubicacion' => 'Jardín'],
      ['codigo' => 'CO-ANT-05368', 'ubicacion' => 'Jericó'],
      ['codigo' => 'CO-ANT-05376', 'ubicacion' => 'La Ceja'],
      ['codigo' => 'CO-ANT-05380', 'ubicacion' => 'La Estrella'],
      ['codigo' => 'CO-ANT-05390', 'ubicacion' => 'La Pintada'],
      ['codigo' => 'CO-ANT-05400', 'ubicacion' => 'La Unión'],
      ['codigo' => 'CO-ANT-05411', 'ubicacion' => 'Liborina'],
      ['codigo' => 'CO-ANT-05425', 'ubicacion' => 'Maceo'],
      ['codigo' => 'CO-ANT-05440', 'ubicacion' => 'Marinilla'],
      ['codigo' => 'CO-ANT-05467', 'ubicacion' => 'Montebello'],
      ['codigo' => 'CO-ANT-05475', 'ubicacion' => 'Murindó'],
      ['codigo' => 'CO-ANT-05480', 'ubicacion' => 'Mutatá'],
      ['codigo' => 'CO-ANT-05483', 'ubicacion' => 'Nariño'],
      ['codigo' => 'CO-ANT-05490', 'ubicacion' => 'Necoclí'],
      ['codigo' => 'CO-ANT-05495', 'ubicacion' => 'Nechí'],
      ['codigo' => 'CO-ANT-05501', 'ubicacion' => 'Olaya'],
      ['codigo' => 'CO-ANT-05541', 'ubicacion' => 'Peñol'],
      ['codigo' => 'CO-ANT-05543', 'ubicacion' => 'Peque'],
      ['codigo' => 'CO-ANT-05576', 'ubicacion' => 'Pueblorrico'],
      ['codigo' => 'CO-ANT-05579', 'ubicacion' => 'Puerto Berrío'],
      ['codigo' => 'CO-ANT-05585', 'ubicacion' => 'Puerto Nare'],
      ['codigo' => 'CO-ANT-05591', 'ubicacion' => 'Puerto Triunfo'],
      ['codigo' => 'CO-ANT-05604', 'ubicacion' => 'Remedios'],
      ['codigo' => 'CO-ANT-05607', 'ubicacion' => 'Retiro'],
      ['codigo' => 'CO-ANT-05615', 'ubicacion' => 'Rionegro'],
      ['codigo' => 'CO-ANT-05628', 'ubicacion' => 'Sabanalarga'],
      ['codigo' => 'CO-ANT-05631', 'ubicacion' => 'Sabaneta'],
      ['codigo' => 'CO-ANT-05642', 'ubicacion' => 'Salgar'],
      ['codigo' => 'CO-ANT-05647', 'ubicacion' => 'San Andrés'],
      ['codigo' => 'CO-ANT-05649', 'ubicacion' => 'San Carlos'],
      ['codigo' => 'CO-ANT-05652', 'ubicacion' => 'San Francisco'],
      ['codigo' => 'CO-ANT-05656', 'ubicacion' => 'San Jerónimo'],
      ['codigo' => 'CO-ANT-05658', 'ubicacion' => 'San José De La Montaña'],
      ['codigo' => 'CO-ANT-05659', 'ubicacion' => 'San Juan De Urabá'],
      ['codigo' => 'CO-ANT-05660', 'ubicacion' => 'San Luis'],
      ['codigo' => 'CO-ANT-05664', 'ubicacion' => 'San Pedro'],
      ['codigo' => 'CO-ANT-05665', 'ubicacion' => 'San Pedro De Uraba'],
      ['codigo' => 'CO-ANT-05667', 'ubicacion' => 'San Rafael'],
      ['codigo' => 'CO-ANT-05670', 'ubicacion' => 'San Roque'],
      ['codigo' => 'CO-ANT-05674', 'ubicacion' => 'San Vicente'],
      ['codigo' => 'CO-ANT-05679', 'ubicacion' => 'Santa Bárbara'],
      ['codigo' => 'CO-ANT-05686', 'ubicacion' => 'Santa Rosa De Osos'],
      ['codigo' => 'CO-ANT-05690', 'ubicacion' => 'Santo Domingo'],
      ['codigo' => 'CO-ANT-05697', 'ubicacion' => 'El Santuario'],
      ['codigo' => 'CO-ANT-05736', 'ubicacion' => 'Segovia'],
      ['codigo' => 'CO-ANT-05756', 'ubicacion' => 'Sonson'],
      ['codigo' => 'CO-ANT-05761', 'ubicacion' => 'Sopetrán'],
      ['codigo' => 'CO-ANT-05789', 'ubicacion' => 'Támesis'],
      ['codigo' => 'CO-ANT-05790', 'ubicacion' => 'Tarazá'],
      ['codigo' => 'CO-ANT-05792', 'ubicacion' => 'Tarso'],
      ['codigo' => 'CO-ANT-05809', 'ubicacion' => 'Titiribí'],
      ['codigo' => 'CO-ANT-05819', 'ubicacion' => 'Toledo'],
      ['codigo' => 'CO-ANT-05837', 'ubicacion' => 'Turbo'],
      ['codigo' => 'CO-ANT-05842', 'ubicacion' => 'Uramita'],
      ['codigo' => 'CO-ANT-05847', 'ubicacion' => 'Urrao'],
      ['codigo' => 'CO-ANT-05854', 'ubicacion' => 'Valdivia'],
      ['codigo' => 'CO-ANT-05856', 'ubicacion' => 'Valparaíso'],
      ['codigo' => 'CO-ANT-05858', 'ubicacion' => 'Vegachí'],
      ['codigo' => 'CO-ANT-05861', 'ubicacion' => 'Venecia'],
      ['codigo' => 'CO-ANT-05873', 'ubicacion' => 'Vigía Del Fuerte'],
      ['codigo' => 'CO-ANT-05885', 'ubicacion' => 'Yalí'],
      ['codigo' => 'CO-ANT-05887', 'ubicacion' => 'Yarumal'],
      ['codigo' => 'CO-ANT-05890', 'ubicacion' => 'Yolombó'],
      ['codigo' => 'CO-ANT-05893', 'ubicacion' => 'Yondó'],
      ['codigo' => 'CO-ANT-05895', 'ubicacion' => 'Zaragoza'],
      ['codigo' => 'CO-ARA', 'ubicacion' => 'Arauca'],
      ['codigo' => 'CO-ARA-81001', 'ubicacion' => 'Arauca'],
      ['codigo' => 'CO-ARA-81065', 'ubicacion' => 'Arauquita'],
      ['codigo' => 'CO-ARA-81220', 'ubicacion' => 'Cravo Norte'],
      ['codigo' => 'CO-ARA-81300', 'ubicacion' => 'Fortul'],
      ['codigo' => 'CO-ARA-81591', 'ubicacion' => 'Puerto Rondón'],
      ['codigo' => 'CO-ARA-81736', 'ubicacion' => 'Saravena'],
      ['codigo' => 'CO-ARA-81794', 'ubicacion' => 'Tame'],
      ['codigo' => 'CO-ATL', 'ubicacion' => 'Atlántico'],
      ['codigo' => 'CO-ATL-08001', 'ubicacion' => 'Barranquilla'],
      ['codigo' => 'CO-ATL-08078', 'ubicacion' => 'Baranoa'],
      ['codigo' => 'CO-ATL-08137', 'ubicacion' => 'Campo De La Cruz'],
      ['codigo' => 'CO-ATL-08141', 'ubicacion' => 'Candelaria'],
      ['codigo' => 'CO-ATL-08296', 'ubicacion' => 'Galapa'],
      ['codigo' => 'CO-ATL-08372', 'ubicacion' => 'Juan De Acosta'],
      ['codigo' => 'CO-ATL-08421', 'ubicacion' => 'Luruaco'],
      ['codigo' => 'CO-ATL-08433', 'ubicacion' => 'Malambo'],
      ['codigo' => 'CO-ATL-08436', 'ubicacion' => 'Manatí'],
      ['codigo' => 'CO-ATL-08520', 'ubicacion' => 'Palmar De Varela'],
      ['codigo' => 'CO-ATL-08549', 'ubicacion' => 'Piojó'],
      ['codigo' => 'CO-ATL-08558', 'ubicacion' => 'Polonuevo'],
      ['codigo' => 'CO-ATL-08560', 'ubicacion' => 'Ponedera'],
      ['codigo' => 'CO-ATL-08573', 'ubicacion' => 'Puerto Colombia'],
      ['codigo' => 'CO-ATL-08606', 'ubicacion' => 'Repelón'],
      ['codigo' => 'CO-ATL-08634', 'ubicacion' => 'Sabanagrande'],
      ['codigo' => 'CO-ATL-08638', 'ubicacion' => 'Sabanalarga'],
      ['codigo' => 'CO-ATL-08675', 'ubicacion' => 'Santa Lucía'],
      ['codigo' => 'CO-ATL-08685', 'ubicacion' => 'Santo Tomás'],
      ['codigo' => 'CO-ATL-08758', 'ubicacion' => 'Soledad'],
      ['codigo' => 'CO-ATL-08770', 'ubicacion' => 'Suan'],
      ['codigo' => 'CO-ATL-08832', 'ubicacion' => 'Tubará'],
      ['codigo' => 'CO-ATL-08849', 'ubicacion' => 'Usiacurí'],
      ['codigo' => 'CO-BOL', 'ubicacion' => 'Bolívar'],
      ['codigo' => 'CO-BOL-13001', 'ubicacion' => 'Cartagena'],
      ['codigo' => 'CO-BOL-13006', 'ubicacion' => 'Achí'],
      ['codigo' => 'CO-BOL-13030', 'ubicacion' => 'Altos Del Rosario'],
      ['codigo' => 'CO-BOL-13042', 'ubicacion' => 'Arenal'],
      ['codigo' => 'CO-BOL-13052', 'ubicacion' => 'Arjona'],
      ['codigo' => 'CO-BOL-13062', 'ubicacion' => 'Arroyohondo'],
      ['codigo' => 'CO-BOL-13074', 'ubicacion' => 'Barranco De Loba'],
      ['codigo' => 'CO-BOL-13140', 'ubicacion' => 'Calamar'],
      ['codigo' => 'CO-BOL-13160', 'ubicacion' => 'Cantagallo'],
      ['codigo' => 'CO-BOL-13188', 'ubicacion' => 'Cicuco'],
      ['codigo' => 'CO-BOL-13212', 'ubicacion' => 'Córdoba'],
      ['codigo' => 'CO-BOL-13222', 'ubicacion' => 'Clemencia'],
      ['codigo' => 'CO-BOL-13244', 'ubicacion' => 'El Carmen De Bolívar'],
      ['codigo' => 'CO-BOL-13248', 'ubicacion' => 'El Guamo'],
      ['codigo' => 'CO-BOL-13268', 'ubicacion' => 'El Peñón'],
      ['codigo' => 'CO-BOL-13300', 'ubicacion' => 'Hatillo De Loba'],
      ['codigo' => 'CO-BOL-13430', 'ubicacion' => 'Magangué'],
      ['codigo' => 'CO-BOL-13433', 'ubicacion' => 'Mahates'],
      ['codigo' => 'CO-BOL-13440', 'ubicacion' => 'Margarita'],
      ['codigo' => 'CO-BOL-13442', 'ubicacion' => 'María La Baja'],
      ['codigo' => 'CO-BOL-13458', 'ubicacion' => 'Montecristo'],
      ['codigo' => 'CO-BOL-13468', 'ubicacion' => 'Mompós'],
      ['codigo' => 'CO-BOL-13473', 'ubicacion' => 'Morales'],
      ['codigo' => 'CO-BOL-13490', 'ubicacion' => 'Norosí'],
      ['codigo' => 'CO-BOL-13549', 'ubicacion' => 'Pinillos'],
      ['codigo' => 'CO-BOL-13580', 'ubicacion' => 'Regidor'],
      ['codigo' => 'CO-BOL-13600', 'ubicacion' => 'Río Viejo'],
      ['codigo' => 'CO-BOL-13620', 'ubicacion' => 'San Cristóbal'],
      ['codigo' => 'CO-BOL-13647', 'ubicacion' => 'San Estanislao'],
      ['codigo' => 'CO-BOL-13650', 'ubicacion' => 'San Fernando'],
      ['codigo' => 'CO-BOL-13654', 'ubicacion' => 'San Jacinto'],
      ['codigo' => 'CO-BOL-13655', 'ubicacion' => 'San Jacinto Del Cauca'],
      ['codigo' => 'CO-BOL-13657', 'ubicacion' => 'San Juan Nepomuceno'],
      ['codigo' => 'CO-BOL-13667', 'ubicacion' => 'San Martín De Loba'],
      ['codigo' => 'CO-BOL-13670', 'ubicacion' => 'San Pablo'],
      ['codigo' => 'CO-BOL-13673', 'ubicacion' => 'Santa Catalina'],
      ['codigo' => 'CO-BOL-13683', 'ubicacion' => 'Santa Rosa'],
      ['codigo' => 'CO-BOL-13688', 'ubicacion' => 'Santa Rosa Del Sur'],
      ['codigo' => 'CO-BOL-13744', 'ubicacion' => 'Simití'],
      ['codigo' => 'CO-BOL-13760', 'ubicacion' => 'Soplaviento'],
      ['codigo' => 'CO-BOL-13780', 'ubicacion' => 'Talaigua Nuevo'],
      ['codigo' => 'CO-BOL-13810', 'ubicacion' => 'Tiquisio'],
      ['codigo' => 'CO-BOL-13836', 'ubicacion' => 'Turbaco'],
      ['codigo' => 'CO-BOL-13838', 'ubicacion' => 'Turbaná'],
      ['codigo' => 'CO-BOL-13873', 'ubicacion' => 'Villanueva'],
      ['codigo' => 'CO-BOL-13894', 'ubicacion' => 'Zambrano'],
      ['codigo' => 'CO-BOY', 'ubicacion' => 'Boyacá'],
      ['codigo' => 'CO-BOY-15001', 'ubicacion' => 'Tunja'],
      ['codigo' => 'CO-BOY-15022', 'ubicacion' => 'Almeida'],
      ['codigo' => 'CO-BOY-15047', 'ubicacion' => 'Aquitania'],
      ['codigo' => 'CO-BOY-15051', 'ubicacion' => 'Arcabuco'],
      ['codigo' => 'CO-BOY-15087', 'ubicacion' => 'Belén'],
      ['codigo' => 'CO-BOY-15090', 'ubicacion' => 'Berbeo'],
      ['codigo' => 'CO-BOY-15092', 'ubicacion' => 'Betéitiva'],
      ['codigo' => 'CO-BOY-15097', 'ubicacion' => 'Boavita'],
      ['codigo' => 'CO-BOY-15104', 'ubicacion' => 'Boyacá'],
      ['codigo' => 'CO-BOY-15106', 'ubicacion' => 'Briceño'],
      ['codigo' => 'CO-BOY-15109', 'ubicacion' => 'Buenavista'],
      ['codigo' => 'CO-BOY-15114', 'ubicacion' => 'Busbanzá'],
      ['codigo' => 'CO-BOY-15131', 'ubicacion' => 'Caldas'],
      ['codigo' => 'CO-BOY-15135', 'ubicacion' => 'Campohermoso'],
      ['codigo' => 'CO-BOY-15162', 'ubicacion' => 'Cerinza'],
      ['codigo' => 'CO-BOY-15172', 'ubicacion' => 'Chinavita'],
      ['codigo' => 'CO-BOY-15176', 'ubicacion' => 'Chiquinquirá'],
      ['codigo' => 'CO-BOY-15180', 'ubicacion' => 'Chiscas'],
      ['codigo' => 'CO-BOY-15183', 'ubicacion' => 'Chita'],
      ['codigo' => 'CO-BOY-15185', 'ubicacion' => 'Chitaraque'],
      ['codigo' => 'CO-BOY-15187', 'ubicacion' => 'Chivatá'],
      ['codigo' => 'CO-BOY-15189', 'ubicacion' => 'Ciénega'],
      ['codigo' => 'CO-BOY-15204', 'ubicacion' => 'Cómbita'],
      ['codigo' => 'CO-BOY-15212', 'ubicacion' => 'Coper'],
      ['codigo' => 'CO-BOY-15215', 'ubicacion' => 'Corrales'],
      ['codigo' => 'CO-BOY-15218', 'ubicacion' => 'Covarachía'],
      ['codigo' => 'CO-BOY-15223', 'ubicacion' => 'Cubará'],
      ['codigo' => 'CO-BOY-15224', 'ubicacion' => 'Cucaita'],
      ['codigo' => 'CO-BOY-15226', 'ubicacion' => 'Cuítiva'],
      ['codigo' => 'CO-BOY-15232', 'ubicacion' => 'Chíquiza'],
      ['codigo' => 'CO-BOY-15236', 'ubicacion' => 'Chivor'],
      ['codigo' => 'CO-BOY-15238', 'ubicacion' => 'Duitama'],
      ['codigo' => 'CO-BOY-15244', 'ubicacion' => 'El Cocuy'],
      ['codigo' => 'CO-BOY-15248', 'ubicacion' => 'El Espino'],
      ['codigo' => 'CO-BOY-15272', 'ubicacion' => 'Firavitoba'],
      ['codigo' => 'CO-BOY-15276', 'ubicacion' => 'Floresta'],
      ['codigo' => 'CO-BOY-15293', 'ubicacion' => 'Gachantivá'],
      ['codigo' => 'CO-BOY-15296', 'ubicacion' => 'Gameza'],
      ['codigo' => 'CO-BOY-15299', 'ubicacion' => 'Garagoa'],
      ['codigo' => 'CO-BOY-15317', 'ubicacion' => 'Guacamayas'],
      ['codigo' => 'CO-BOY-15322', 'ubicacion' => 'Guateque'],
      ['codigo' => 'CO-BOY-15325', 'ubicacion' => 'Guayatá'],
      ['codigo' => 'CO-BOY-15332', 'ubicacion' => 'Güicán'],
      ['codigo' => 'CO-BOY-15362', 'ubicacion' => 'Iza'],
      ['codigo' => 'CO-BOY-15367', 'ubicacion' => 'Jenesano'],
      ['codigo' => 'CO-BOY-15368', 'ubicacion' => 'Jericó'],
      ['codigo' => 'CO-BOY-15377', 'ubicacion' => 'Labranzagrande'],
      ['codigo' => 'CO-BOY-15380', 'ubicacion' => 'La Capilla'],
      ['codigo' => 'CO-BOY-15401', 'ubicacion' => 'La Victoria'],
      ['codigo' => 'CO-BOY-15403', 'ubicacion' => 'La Uvita'],
      ['codigo' => 'CO-BOY-15407', 'ubicacion' => 'Villa De Leyva'],
      ['codigo' => 'CO-BOY-15425', 'ubicacion' => 'Macanal'],
      ['codigo' => 'CO-BOY-15442', 'ubicacion' => 'Maripí'],
      ['codigo' => 'CO-BOY-15455', 'ubicacion' => 'Miraflores'],
      ['codigo' => 'CO-BOY-15464', 'ubicacion' => 'Mongua'],
      ['codigo' => 'CO-BOY-15466', 'ubicacion' => 'Monguí'],
      ['codigo' => 'CO-BOY-15469', 'ubicacion' => 'Moniquirá'],
      ['codigo' => 'CO-BOY-15476', 'ubicacion' => 'Motavita'],
      ['codigo' => 'CO-BOY-15480', 'ubicacion' => 'Muzo'],
      ['codigo' => 'CO-BOY-15491', 'ubicacion' => 'Nobsa'],
      ['codigo' => 'CO-BOY-15494', 'ubicacion' => 'Nuevo Colón'],
      ['codigo' => 'CO-BOY-15500', 'ubicacion' => 'Oicatá'],
      ['codigo' => 'CO-BOY-15507', 'ubicacion' => 'Otanche'],
      ['codigo' => 'CO-BOY-15511', 'ubicacion' => 'Pachavita'],
      ['codigo' => 'CO-BOY-15514', 'ubicacion' => 'Páez'],
      ['codigo' => 'CO-BOY-15516', 'ubicacion' => 'Paipa'],
      ['codigo' => 'CO-BOY-15518', 'ubicacion' => 'Pajarito'],
      ['codigo' => 'CO-BOY-15522', 'ubicacion' => 'Panqueba'],
      ['codigo' => 'CO-BOY-15531', 'ubicacion' => 'Pauna'],
      ['codigo' => 'CO-BOY-15533', 'ubicacion' => 'Paya'],
      ['codigo' => 'CO-BOY-15537', 'ubicacion' => 'Paz De Río'],
      ['codigo' => 'CO-BOY-15542', 'ubicacion' => 'Pesca'],
      ['codigo' => 'CO-BOY-15550', 'ubicacion' => 'Pisba'],
      ['codigo' => 'CO-BOY-15572', 'ubicacion' => 'Puerto Boyacá'],
      ['codigo' => 'CO-BOY-15580', 'ubicacion' => 'Quípama'],
      ['codigo' => 'CO-BOY-15599', 'ubicacion' => 'Ramiriquí'],
      ['codigo' => 'CO-BOY-15600', 'ubicacion' => 'Ráquira'],
      ['codigo' => 'CO-BOY-15621', 'ubicacion' => 'Rondón'],
      ['codigo' => 'CO-BOY-15632', 'ubicacion' => 'Saboyá'],
      ['codigo' => 'CO-BOY-15638', 'ubicacion' => 'Sáchica'],
      ['codigo' => 'CO-BOY-15646', 'ubicacion' => 'Samacá'],
      ['codigo' => 'CO-BOY-15660', 'ubicacion' => 'San Eduardo'],
      ['codigo' => 'CO-BOY-15664', 'ubicacion' => 'San José De Pare'],
      ['codigo' => 'CO-BOY-15667', 'ubicacion' => 'San Luis De Gaceno'],
      ['codigo' => 'CO-BOY-15673', 'ubicacion' => 'San Mateo'],
      ['codigo' => 'CO-BOY-15676', 'ubicacion' => 'San Miguel De Sema'],
      ['codigo' => 'CO-BOY-15681', 'ubicacion' => 'San Pablo De Borbur'],
      ['codigo' => 'CO-BOY-15686', 'ubicacion' => 'Santana'],
      ['codigo' => 'CO-BOY-15690', 'ubicacion' => 'Santa María'],
      ['codigo' => 'CO-BOY-15693', 'ubicacion' => 'Santa Rosa De Viterbo'],
      ['codigo' => 'CO-BOY-15696', 'ubicacion' => 'Santa Sofía'],
      ['codigo' => 'CO-BOY-15720', 'ubicacion' => 'Sativanorte'],
      ['codigo' => 'CO-BOY-15723', 'ubicacion' => 'Sativasur'],
      ['codigo' => 'CO-BOY-15740', 'ubicacion' => 'Siachoque'],
      ['codigo' => 'CO-BOY-15753', 'ubicacion' => 'Soatá'],
      ['codigo' => 'CO-BOY-15755', 'ubicacion' => 'Socotá'],
      ['codigo' => 'CO-BOY-15757', 'ubicacion' => 'Socha'],
      ['codigo' => 'CO-BOY-15759', 'ubicacion' => 'Sogamoso'],
      ['codigo' => 'CO-BOY-15761', 'ubicacion' => 'Somondoco'],
      ['codigo' => 'CO-BOY-15762', 'ubicacion' => 'Sora'],
      ['codigo' => 'CO-BOY-15763', 'ubicacion' => 'Sotaquirá'],
      ['codigo' => 'CO-BOY-15764', 'ubicacion' => 'Soracá'],
      ['codigo' => 'CO-BOY-15774', 'ubicacion' => 'Susacón'],
      ['codigo' => 'CO-BOY-15776', 'ubicacion' => 'Sutamarchán'],
      ['codigo' => 'CO-BOY-15778', 'ubicacion' => 'Sutatenza'],
      ['codigo' => 'CO-BOY-15790', 'ubicacion' => 'Tasco'],
      ['codigo' => 'CO-BOY-15798', 'ubicacion' => 'Tenza'],
      ['codigo' => 'CO-BOY-15804', 'ubicacion' => 'Tibaná'],
      ['codigo' => 'CO-BOY-15806', 'ubicacion' => 'Tibasosa'],
      ['codigo' => 'CO-BOY-15808', 'ubicacion' => 'Tinjacá'],
      ['codigo' => 'CO-BOY-15810', 'ubicacion' => 'Tipacoque'],
      ['codigo' => 'CO-BOY-15814', 'ubicacion' => 'Toca'],
      ['codigo' => 'CO-BOY-15816', 'ubicacion' => 'Togüí'],
      ['codigo' => 'CO-BOY-15820', 'ubicacion' => 'Tópaga'],
      ['codigo' => 'CO-BOY-15822', 'ubicacion' => 'Tota'],
      ['codigo' => 'CO-BOY-15832', 'ubicacion' => 'Tununguá'],
      ['codigo' => 'CO-BOY-15835', 'ubicacion' => 'Turmequé'],
      ['codigo' => 'CO-BOY-15837', 'ubicacion' => 'Tuta'],
      ['codigo' => 'CO-BOY-15839', 'ubicacion' => 'Tutazá'],
      ['codigo' => 'CO-BOY-15842', 'ubicacion' => 'Umbita'],
      ['codigo' => 'CO-BOY-15861', 'ubicacion' => 'Ventaquemada'],
      ['codigo' => 'CO-BOY-15879', 'ubicacion' => 'Viracachá'],
      ['codigo' => 'CO-BOY-15897', 'ubicacion' => 'Zetaquira'],
      ['codigo' => 'CO-CAL', 'ubicacion' => 'Caldas'],
      ['codigo' => 'CO-CAL-17001', 'ubicacion' => 'Manizales'],
      ['codigo' => 'CO-CAL-17013', 'ubicacion' => 'Aguadas'],
      ['codigo' => 'CO-CAL-17042', 'ubicacion' => 'Anserma'],
      ['codigo' => 'CO-CAL-17050', 'ubicacion' => 'Aranzazu'],
      ['codigo' => 'CO-CAL-17088', 'ubicacion' => 'Belalcázar'],
      ['codigo' => 'CO-CAL-17174', 'ubicacion' => 'Chinchiná'],
      ['codigo' => 'CO-CAL-17272', 'ubicacion' => 'Filadelfia'],
      ['codigo' => 'CO-CAL-17380', 'ubicacion' => 'La Dorada'],
      ['codigo' => 'CO-CAL-17388', 'ubicacion' => 'La Merced'],
      ['codigo' => 'CO-CAL-17433', 'ubicacion' => 'Manzanares'],
      ['codigo' => 'CO-CAL-17442', 'ubicacion' => 'Marmato'],
      ['codigo' => 'CO-CAL-17444', 'ubicacion' => 'Marquetalia'],
      ['codigo' => 'CO-CAL-17446', 'ubicacion' => 'Marulanda'],
      ['codigo' => 'CO-CAL-17486', 'ubicacion' => 'Neira'],
      ['codigo' => 'CO-CAL-17495', 'ubicacion' => 'Norcasia'],
      ['codigo' => 'CO-CAL-17513', 'ubicacion' => 'Pácora'],
      ['codigo' => 'CO-CAL-17524', 'ubicacion' => 'Palestina'],
      ['codigo' => 'CO-CAL-17541', 'ubicacion' => 'Pensilvania'],
      ['codigo' => 'CO-CAL-17614', 'ubicacion' => 'Riosucio'],
      ['codigo' => 'CO-CAL-17616', 'ubicacion' => 'Risaralda'],
      ['codigo' => 'CO-CAL-17653', 'ubicacion' => 'Salamina'],
      ['codigo' => 'CO-CAL-17662', 'ubicacion' => 'Samaná'],
      ['codigo' => 'CO-CAL-17665', 'ubicacion' => 'San José'],
      ['codigo' => 'CO-CAL-17777', 'ubicacion' => 'Supía'],
      ['codigo' => 'CO-CAL-17867', 'ubicacion' => 'Victoria'],
      ['codigo' => 'CO-CAL-17873', 'ubicacion' => 'Villamaría'],
      ['codigo' => 'CO-CAL-17877', 'ubicacion' => 'Viterbo'],
      ['codigo' => 'CO-CAQ', 'ubicacion' => 'Caquetá'],
      ['codigo' => 'CO-CAQ-18001', 'ubicacion' => 'Florencia'],
      ['codigo' => 'CO-CAQ-18029', 'ubicacion' => 'Albania'],
      ['codigo' => 'CO-CAQ-18094', 'ubicacion' => 'Belén De Los Andaquies'],
      ['codigo' => 'CO-CAQ-18150', 'ubicacion' => 'Cartagena Del Chairá'],
      ['codigo' => 'CO-CAQ-18205', 'ubicacion' => 'Curillo'],
      ['codigo' => 'CO-CAQ-18247', 'ubicacion' => 'El Doncello'],
      ['codigo' => 'CO-CAQ-18256', 'ubicacion' => 'El Paujil'],
      ['codigo' => 'CO-CAQ-18410', 'ubicacion' => 'La Montañita'],
      ['codigo' => 'CO-CAQ-18460', 'ubicacion' => 'Milán'],
      ['codigo' => 'CO-CAQ-18479', 'ubicacion' => 'Morelia'],
      ['codigo' => 'CO-CAQ-18592', 'ubicacion' => 'Puerto Rico'],
      ['codigo' => 'CO-CAQ-18610', 'ubicacion' => 'San José Del Fragua'],
      ['codigo' => 'CO-CAQ-18753', 'ubicacion' => 'San Vicente Del Caguán'],
      ['codigo' => 'CO-CAQ-18756', 'ubicacion' => 'Solano'],
      ['codigo' => 'CO-CAQ-18785', 'ubicacion' => 'Solita'],
      ['codigo' => 'CO-CAQ-18860', 'ubicacion' => 'Valparaíso'],
      ['codigo' => 'CO-CAS', 'ubicacion' => 'Casanare'],
      ['codigo' => 'CO-CAS-85001', 'ubicacion' => 'Yopal'],
      ['codigo' => 'CO-CAS-85010', 'ubicacion' => 'Aguazul'],
      ['codigo' => 'CO-CAS-85015', 'ubicacion' => 'Chameza'],
      ['codigo' => 'CO-CAS-85125', 'ubicacion' => 'Hato Corozal'],
      ['codigo' => 'CO-CAS-85136', 'ubicacion' => 'La Salina'],
      ['codigo' => 'CO-CAS-85139', 'ubicacion' => 'Maní'],
      ['codigo' => 'CO-CAS-85162', 'ubicacion' => 'Monterrey'],
      ['codigo' => 'CO-CAS-85225', 'ubicacion' => 'Nunchía'],
      ['codigo' => 'CO-CAS-85230', 'ubicacion' => 'Orocué'],
      ['codigo' => 'CO-CAS-85250', 'ubicacion' => 'Paz De Ariporo'],
      ['codigo' => 'CO-CAS-85263', 'ubicacion' => 'Pore'],
      ['codigo' => 'CO-CAS-85279', 'ubicacion' => 'Recetor'],
      ['codigo' => 'CO-CAS-85300', 'ubicacion' => 'Sabanalarga'],
      ['codigo' => 'CO-CAS-85315', 'ubicacion' => 'Sácama'],
      ['codigo' => 'CO-CAS-85325', 'ubicacion' => 'San Luis De Palenque'],
      ['codigo' => 'CO-CAS-85400', 'ubicacion' => 'Támara'],
      ['codigo' => 'CO-CAS-85410', 'ubicacion' => 'Tauramena'],
      ['codigo' => 'CO-CAS-85430', 'ubicacion' => 'Trinidad'],
      ['codigo' => 'CO-CAS-85440', 'ubicacion' => 'Villanueva'],
      ['codigo' => 'CO-CAU', 'ubicacion' => 'Cauca'],
      ['codigo' => 'CO-CAU-19001', 'ubicacion' => 'Popayán'],
      ['codigo' => 'CO-CAU-19022', 'ubicacion' => 'Almaguer'],
      ['codigo' => 'CO-CAU-19050', 'ubicacion' => 'Argelia'],
      ['codigo' => 'CO-CAU-19075', 'ubicacion' => 'Balboa'],
      ['codigo' => 'CO-CAU-19100', 'ubicacion' => 'Bolívar'],
      ['codigo' => 'CO-CAU-19110', 'ubicacion' => 'Buenos Aires'],
      ['codigo' => 'CO-CAU-19130', 'ubicacion' => 'Cajibío'],
      ['codigo' => 'CO-CAU-19137', 'ubicacion' => 'Caldono'],
      ['codigo' => 'CO-CAU-19142', 'ubicacion' => 'Caloto'],
      ['codigo' => 'CO-CAU-19212', 'ubicacion' => 'Corinto'],
      ['codigo' => 'CO-CAU-19256', 'ubicacion' => 'El Tambo'],
      ['codigo' => 'CO-CAU-19290', 'ubicacion' => 'Florencia'],
      ['codigo' => 'CO-CAU-19300', 'ubicacion' => 'Guachené'],
      ['codigo' => 'CO-CAU-19318', 'ubicacion' => 'Guapi'],
      ['codigo' => 'CO-CAU-19355', 'ubicacion' => 'Inzá'],
      ['codigo' => 'CO-CAU-19364', 'ubicacion' => 'Jambaló'],
      ['codigo' => 'CO-CAU-19392', 'ubicacion' => 'La Sierra'],
      ['codigo' => 'CO-CAU-19397', 'ubicacion' => 'La Vega'],
      ['codigo' => 'CO-CAU-19418', 'ubicacion' => 'López'],
      ['codigo' => 'CO-CAU-19450', 'ubicacion' => 'Mercaderes'],
      ['codigo' => 'CO-CAU-19455', 'ubicacion' => 'Miranda'],
      ['codigo' => 'CO-CAU-19473', 'ubicacion' => 'Morales'],
      ['codigo' => 'CO-CAU-19513', 'ubicacion' => 'Padilla'],
      ['codigo' => 'CO-CAU-19517', 'ubicacion' => 'Paez'],
      ['codigo' => 'CO-CAU-19532', 'ubicacion' => 'Patía'],
      ['codigo' => 'CO-CAU-19533', 'ubicacion' => 'Piamonte'],
      ['codigo' => 'CO-CAU-19548', 'ubicacion' => 'Piendamó'],
      ['codigo' => 'CO-CAU-19573', 'ubicacion' => 'Puerto Tejada'],
      ['codigo' => 'CO-CAU-19585', 'ubicacion' => 'Puracé'],
      ['codigo' => 'CO-CAU-19622', 'ubicacion' => 'Rosas'],
      ['codigo' => 'CO-CAU-19693', 'ubicacion' => 'San Sebastián'],
      ['codigo' => 'CO-CAU-19698', 'ubicacion' => 'Santander De Quilichao'],
      ['codigo' => 'CO-CAU-19701', 'ubicacion' => 'Santa Rosa'],
      ['codigo' => 'CO-CAU-19743', 'ubicacion' => 'Silvia'],
      ['codigo' => 'CO-CAU-19760', 'ubicacion' => 'Sotara'],
      ['codigo' => 'CO-CAU-19780', 'ubicacion' => 'Suárez'],
      ['codigo' => 'CO-CAU-19785', 'ubicacion' => 'Sucre'],
      ['codigo' => 'CO-CAU-19807', 'ubicacion' => 'Timbío'],
      ['codigo' => 'CO-CAU-19809', 'ubicacion' => 'Timbiquí'],
      ['codigo' => 'CO-CAU-19821', 'ubicacion' => 'Toribio'],
      ['codigo' => 'CO-CAU-19824', 'ubicacion' => 'Totoró'],
      ['codigo' => 'CO-CAU-19845', 'ubicacion' => 'Villa Rica'],
      ['codigo' => 'CO-CES', 'ubicacion' => 'Cesar'],
      ['codigo' => 'CO-CES-20001', 'ubicacion' => 'Valledupar'],
      ['codigo' => 'CO-CES-20011', 'ubicacion' => 'Aguachica'],
      ['codigo' => 'CO-CES-20013', 'ubicacion' => 'Agustín Codazzi'],
      ['codigo' => 'CO-CES-20032', 'ubicacion' => 'Astrea'],
      ['codigo' => 'CO-CES-20045', 'ubicacion' => 'Becerril'],
      ['codigo' => 'CO-CES-20060', 'ubicacion' => 'Bosconia'],
      ['codigo' => 'CO-CES-20175', 'ubicacion' => 'Chimichagua'],
      ['codigo' => 'CO-CES-20178', 'ubicacion' => 'Chiriguaná'],
      ['codigo' => 'CO-CES-20228', 'ubicacion' => 'Curumaní'],
      ['codigo' => 'CO-CES-20238', 'ubicacion' => 'El Copey'],
      ['codigo' => 'CO-CES-20250', 'ubicacion' => 'El Paso'],
      ['codigo' => 'CO-CES-20295', 'ubicacion' => 'Gamarra'],
      ['codigo' => 'CO-CES-20310', 'ubicacion' => 'González'],
      ['codigo' => 'CO-CES-20383', 'ubicacion' => 'La Gloria'],
      ['codigo' => 'CO-CES-20400', 'ubicacion' => 'La Jagua De Ibirico'],
      ['codigo' => 'CO-CES-20443', 'ubicacion' => 'Manaure'],
      ['codigo' => 'CO-CES-20517', 'ubicacion' => 'Pailitas'],
      ['codigo' => 'CO-CES-20550', 'ubicacion' => 'Pelaya'],
      ['codigo' => 'CO-CES-20570', 'ubicacion' => 'Pueblo Bello'],
      ['codigo' => 'CO-CES-20614', 'ubicacion' => 'Río De Oro'],
      ['codigo' => 'CO-CES-20621', 'ubicacion' => 'La Paz'],
      ['codigo' => 'CO-CES-20710', 'ubicacion' => 'San Alberto'],
      ['codigo' => 'CO-CES-20750', 'ubicacion' => 'San Diego'],
      ['codigo' => 'CO-CES-20770', 'ubicacion' => 'San Martín'],
      ['codigo' => 'CO-CES-20787', 'ubicacion' => 'Tamalameque'],
      ['codigo' => 'CO-COR', 'ubicacion' => 'Córdoba'],
      ['codigo' => 'CO-COR-23001', 'ubicacion' => 'Montería'],
      ['codigo' => 'CO-COR-23068', 'ubicacion' => 'Ayapel'],
      ['codigo' => 'CO-COR-23079', 'ubicacion' => 'Buenavista'],
      ['codigo' => 'CO-COR-23090', 'ubicacion' => 'Canalete'],
      ['codigo' => 'CO-COR-23162', 'ubicacion' => 'Cereté'],
      ['codigo' => 'CO-COR-23168', 'ubicacion' => 'Chimá'],
      ['codigo' => 'CO-COR-23182', 'ubicacion' => 'Chinú'],
      ['codigo' => 'CO-COR-23189', 'ubicacion' => 'Ciénaga De Oro'],
      ['codigo' => 'CO-COR-23300', 'ubicacion' => 'Cotorra'],
      ['codigo' => 'CO-COR-23350', 'ubicacion' => 'La Apartada'],
      ['codigo' => 'CO-COR-23417', 'ubicacion' => 'Lorica'],
      ['codigo' => 'CO-COR-23419', 'ubicacion' => 'Los Córdobas'],
      ['codigo' => 'CO-COR-23464', 'ubicacion' => 'Momil'],
      ['codigo' => 'CO-COR-23466', 'ubicacion' => 'Montelíbano'],
      ['codigo' => 'CO-COR-23500', 'ubicacion' => 'Moñitos'],
      ['codigo' => 'CO-COR-23555', 'ubicacion' => 'Planeta Rica'],
      ['codigo' => 'CO-COR-23570', 'ubicacion' => 'Pueblo Nuevo'],
      ['codigo' => 'CO-COR-23574', 'ubicacion' => 'Puerto Escondido'],
      ['codigo' => 'CO-COR-23580', 'ubicacion' => 'Puerto Libertador'],
      ['codigo' => 'CO-COR-23586', 'ubicacion' => 'Purísima'],
      ['codigo' => 'CO-COR-23660', 'ubicacion' => 'Sahagún'],
      ['codigo' => 'CO-COR-23670', 'ubicacion' => 'San Andrés Sotavento'],
      ['codigo' => 'CO-COR-23672', 'ubicacion' => 'San Antero'],
      ['codigo' => 'CO-COR-23675', 'ubicacion' => 'San Bernardo Del Viento'],
      ['codigo' => 'CO-COR-23678', 'ubicacion' => 'San Carlos'],
      ['codigo' => 'CO-COR-23682', 'ubicacion' => 'San José de Uré'],
      ['codigo' => 'CO-COR-23686', 'ubicacion' => 'San Pelayo'],
      ['codigo' => 'CO-COR-23807', 'ubicacion' => 'Tierralta'],
      ['codigo' => 'CO-COR-23855', 'ubicacion' => 'Valencia'],
      ['codigo' => 'CO-CUN', 'ubicacion' => 'Cundinamarca'],
      ['codigo' => 'CO-CUN-25001', 'ubicacion' => 'Agua De Dios'],
      ['codigo' => 'CO-CUN-25019', 'ubicacion' => 'Albán'],
      ['codigo' => 'CO-CUN-25035', 'ubicacion' => 'Anapoima'],
      ['codigo' => 'CO-CUN-25040', 'ubicacion' => 'Anolaima'],
      ['codigo' => 'CO-CUN-25053', 'ubicacion' => 'Arbeláez'],
      ['codigo' => 'CO-CUN-25086', 'ubicacion' => 'Beltrán'],
      ['codigo' => 'CO-CUN-25095', 'ubicacion' => 'Bituima'],
      ['codigo' => 'CO-CUN-25099', 'ubicacion' => 'Bojacá'],
      ['codigo' => 'CO-CUN-25120', 'ubicacion' => 'Cabrera'],
      ['codigo' => 'CO-CUN-25123', 'ubicacion' => 'Cachipay'],
      ['codigo' => 'CO-CUN-25126', 'ubicacion' => 'Cajicá'],
      ['codigo' => 'CO-CUN-25148', 'ubicacion' => 'Caparrapí'],
      ['codigo' => 'CO-CUN-25151', 'ubicacion' => 'Caqueza'],
      ['codigo' => 'CO-CUN-25154', 'ubicacion' => 'Carmen De Carupa'],
      ['codigo' => 'CO-CUN-25168', 'ubicacion' => 'Chaguaní'],
      ['codigo' => 'CO-CUN-25175', 'ubicacion' => 'Chía'],
      ['codigo' => 'CO-CUN-25178', 'ubicacion' => 'Chipaque'],
      ['codigo' => 'CO-CUN-25181', 'ubicacion' => 'Choachí'],
      ['codigo' => 'CO-CUN-25183', 'ubicacion' => 'Chocontá'],
      ['codigo' => 'CO-CUN-25200', 'ubicacion' => 'Cogua'],
      ['codigo' => 'CO-CUN-25214', 'ubicacion' => 'Cota'],
      ['codigo' => 'CO-CUN-25224', 'ubicacion' => 'Cucunubá'],
      ['codigo' => 'CO-CUN-25245', 'ubicacion' => 'El Colegio'],
      ['codigo' => 'CO-CUN-25258', 'ubicacion' => 'El Peñón'],
      ['codigo' => 'CO-CUN-25260', 'ubicacion' => 'El Rosal'],
      ['codigo' => 'CO-CUN-25269', 'ubicacion' => 'Facatativá'],
      ['codigo' => 'CO-CUN-25279', 'ubicacion' => 'Fomeque'],
      ['codigo' => 'CO-CUN-25281', 'ubicacion' => 'Fosca'],
      ['codigo' => 'CO-CUN-25286', 'ubicacion' => 'Funza'],
      ['codigo' => 'CO-CUN-25288', 'ubicacion' => 'Fúquene'],
      ['codigo' => 'CO-CUN-25290', 'ubicacion' => 'Fusagasugá'],
      ['codigo' => 'CO-CUN-25293', 'ubicacion' => 'Gachala'],
      ['codigo' => 'CO-CUN-25295', 'ubicacion' => 'Gachancipá'],
      ['codigo' => 'CO-CUN-25297', 'ubicacion' => 'Gachetá'],
      ['codigo' => 'CO-CUN-25299', 'ubicacion' => 'Gama'],
      ['codigo' => 'CO-CUN-25307', 'ubicacion' => 'Girardot'],
      ['codigo' => 'CO-CUN-25312', 'ubicacion' => 'Granada'],
      ['codigo' => 'CO-CUN-25317', 'ubicacion' => 'Guachetá'],
      ['codigo' => 'CO-CUN-25320', 'ubicacion' => 'Guaduas'],
      ['codigo' => 'CO-CUN-25322', 'ubicacion' => 'Guasca'],
      ['codigo' => 'CO-CUN-25324', 'ubicacion' => 'Guataquí'],
      ['codigo' => 'CO-CUN-25326', 'ubicacion' => 'Guatavita'],
      ['codigo' => 'CO-CUN-25328', 'ubicacion' => 'Guayabal De Siquima'],
      ['codigo' => 'CO-CUN-25335', 'ubicacion' => 'Guayabetal'],
      ['codigo' => 'CO-CUN-25339', 'ubicacion' => 'Gutiérrez'],
      ['codigo' => 'CO-CUN-25368', 'ubicacion' => 'Jerusalén'],
      ['codigo' => 'CO-CUN-25372', 'ubicacion' => 'Junín'],
      ['codigo' => 'CO-CUN-25377', 'ubicacion' => 'La Calera'],
      ['codigo' => 'CO-CUN-25386', 'ubicacion' => 'La Mesa'],
      ['codigo' => 'CO-CUN-25394', 'ubicacion' => 'La Palma'],
      ['codigo' => 'CO-CUN-25398', 'ubicacion' => 'La Peña'],
      ['codigo' => 'CO-CUN-25402', 'ubicacion' => 'La Vega'],
      ['codigo' => 'CO-CUN-25407', 'ubicacion' => 'Lenguazaque'],
      ['codigo' => 'CO-CUN-25426', 'ubicacion' => 'Macheta'],
      ['codigo' => 'CO-CUN-25430', 'ubicacion' => 'Madrid'],
      ['codigo' => 'CO-CUN-25436', 'ubicacion' => 'Manta'],
      ['codigo' => 'CO-CUN-25438', 'ubicacion' => 'Medina'],
      ['codigo' => 'CO-CUN-25473', 'ubicacion' => 'Mosquera'],
      ['codigo' => 'CO-CUN-25483', 'ubicacion' => 'Nariño'],
      ['codigo' => 'CO-CUN-25486', 'ubicacion' => 'Nemocón'],
      ['codigo' => 'CO-CUN-25488', 'ubicacion' => 'Nilo'],
      ['codigo' => 'CO-CUN-25489', 'ubicacion' => 'Nimaima'],
      ['codigo' => 'CO-CUN-25491', 'ubicacion' => 'Nocaima'],
      ['codigo' => 'CO-CUN-25506', 'ubicacion' => 'Venecia'],
      ['codigo' => 'CO-CUN-25513', 'ubicacion' => 'Pacho'],
      ['codigo' => 'CO-CUN-25518', 'ubicacion' => 'Paime'],
      ['codigo' => 'CO-CUN-25524', 'ubicacion' => 'Pandi'],
      ['codigo' => 'CO-CUN-25530', 'ubicacion' => 'Paratebueno'],
      ['codigo' => 'CO-CUN-25535', 'ubicacion' => 'Pasca'],
      ['codigo' => 'CO-CUN-25572', 'ubicacion' => 'Puerto Salgar'],
      ['codigo' => 'CO-CUN-25580', 'ubicacion' => 'Pulí'],
      ['codigo' => 'CO-CUN-25592', 'ubicacion' => 'Quebradanegra'],
      ['codigo' => 'CO-CUN-25594', 'ubicacion' => 'Quetame'],
      ['codigo' => 'CO-CUN-25596', 'ubicacion' => 'Quipile'],
      ['codigo' => 'CO-CUN-25599', 'ubicacion' => 'Apulo'],
      ['codigo' => 'CO-CUN-25612', 'ubicacion' => 'Ricaurte'],
      ['codigo' => 'CO-CUN-25645', 'ubicacion' => 'San Antonio Del Tequendama'],
      ['codigo' => 'CO-CUN-25649', 'ubicacion' => 'San Bernardo'],
      ['codigo' => 'CO-CUN-25653', 'ubicacion' => 'San Cayetano'],
      ['codigo' => 'CO-CUN-25658', 'ubicacion' => 'San Francisco'],
      ['codigo' => 'CO-CUN-25662', 'ubicacion' => 'San Juan De Río Seco'],
      ['codigo' => 'CO-CUN-25718', 'ubicacion' => 'Sasaima'],
      ['codigo' => 'CO-CUN-25736', 'ubicacion' => 'Sesquilé'],
      ['codigo' => 'CO-CUN-25740', 'ubicacion' => 'Sibaté'],
      ['codigo' => 'CO-CUN-25743', 'ubicacion' => 'Silvania'],
      ['codigo' => 'CO-CUN-25745', 'ubicacion' => 'Simijaca'],
      ['codigo' => 'CO-CUN-25754', 'ubicacion' => 'Soacha'],
      ['codigo' => 'CO-CUN-25758', 'ubicacion' => 'Sopó'],
      ['codigo' => 'CO-CUN-25769', 'ubicacion' => 'Subachoque'],
      ['codigo' => 'CO-CUN-25772', 'ubicacion' => 'Suesca'],
      ['codigo' => 'CO-CUN-25777', 'ubicacion' => 'Supatá'],
      ['codigo' => 'CO-CUN-25779', 'ubicacion' => 'Susa'],
      ['codigo' => 'CO-CUN-25781', 'ubicacion' => 'Sutatausa'],
      ['codigo' => 'CO-CUN-25785', 'ubicacion' => 'Tabio'],
      ['codigo' => 'CO-CUN-25793', 'ubicacion' => 'Tausa'],
      ['codigo' => 'CO-CUN-25797', 'ubicacion' => 'Tena'],
      ['codigo' => 'CO-CUN-25799', 'ubicacion' => 'Tenjo'],
      ['codigo' => 'CO-CUN-25805', 'ubicacion' => 'Tibacuy'],
      ['codigo' => 'CO-CUN-25807', 'ubicacion' => 'Tibirita'],
      ['codigo' => 'CO-CUN-25815', 'ubicacion' => 'Tocaima'],
      ['codigo' => 'CO-CUN-25817', 'ubicacion' => 'Tocancipá'],
      ['codigo' => 'CO-CUN-25823', 'ubicacion' => 'Topaipí'],
      ['codigo' => 'CO-CUN-25839', 'ubicacion' => 'Ubalá'],
      ['codigo' => 'CO-CUN-25841', 'ubicacion' => 'Ubaque'],
      ['codigo' => 'CO-CUN-25843', 'ubicacion' => 'Villa De San Diego De Ubate'],
      ['codigo' => 'CO-CUN-25845', 'ubicacion' => 'Une'],
      ['codigo' => 'CO-CUN-25851', 'ubicacion' => 'Útica'],
      ['codigo' => 'CO-CUN-25862', 'ubicacion' => 'Vergara'],
      ['codigo' => 'CO-CUN-25867', 'ubicacion' => 'Vianí'],
      ['codigo' => 'CO-CUN-25871', 'ubicacion' => 'Villagómez'],
      ['codigo' => 'CO-CUN-25873', 'ubicacion' => 'Villapinzón'],
      ['codigo' => 'CO-CUN-25875', 'ubicacion' => 'Villeta'],
      ['codigo' => 'CO-CUN-25878', 'ubicacion' => 'Viotá'],
      ['codigo' => 'CO-CUN-25885', 'ubicacion' => 'Yacopí'],
      ['codigo' => 'CO-CUN-25898', 'ubicacion' => 'Zipacón'],
      ['codigo' => 'CO-CUN-25899', 'ubicacion' => 'Zipaquirá'],
      ['codigo' => 'CO-CHO', 'ubicacion' => 'Chocó'],
      ['codigo' => 'CO-CHO-27001', 'ubicacion' => 'Quibdó'],
      ['codigo' => 'CO-CHO-27006', 'ubicacion' => 'Acandí'],
      ['codigo' => 'CO-CHO-27025', 'ubicacion' => 'Alto Baudo'],
      ['codigo' => 'CO-CHO-27050', 'ubicacion' => 'Atrato'],
      ['codigo' => 'CO-CHO-27073', 'ubicacion' => 'Bagadó'],
      ['codigo' => 'CO-CHO-27075', 'ubicacion' => 'Bahía Solano'],
      ['codigo' => 'CO-CHO-27077', 'ubicacion' => 'Bajo Baudó'],
      ['codigo' => 'CO-CHO-27086', 'ubicacion' => 'Belén De Bajirá'],
      ['codigo' => 'CO-CHO-27099', 'ubicacion' => 'Bojaya'],
      ['codigo' => 'CO-CHO-27135', 'ubicacion' => 'El Cantón Del San Pablo'],
      ['codigo' => 'CO-CHO-27150', 'ubicacion' => 'Carmen Del Darien'],
      ['codigo' => 'CO-CHO-27160', 'ubicacion' => 'Cértegui'],
      ['codigo' => 'CO-CHO-27205', 'ubicacion' => 'Condoto'],
      ['codigo' => 'CO-CHO-27245', 'ubicacion' => 'El Carmen De Atrato'],
      ['codigo' => 'CO-CHO-27250', 'ubicacion' => 'El Litoral Del San Juan'],
      ['codigo' => 'CO-CHO-27361', 'ubicacion' => 'Istmina'],
      ['codigo' => 'CO-CHO-27372', 'ubicacion' => 'Juradó'],
      ['codigo' => 'CO-CHO-27413', 'ubicacion' => 'Lloró'],
      ['codigo' => 'CO-CHO-27425', 'ubicacion' => 'Medio Atrato'],
      ['codigo' => 'CO-CHO-27430', 'ubicacion' => 'Medio Baudó'],
      ['codigo' => 'CO-CHO-27450', 'ubicacion' => 'Medio San Juan'],
      ['codigo' => 'CO-CHO-27491', 'ubicacion' => 'Nóvita'],
      ['codigo' => 'CO-CHO-27495', 'ubicacion' => 'Nuquí'],
      ['codigo' => 'CO-CHO-27580', 'ubicacion' => 'Río Iro'],
      ['codigo' => 'CO-CHO-27600', 'ubicacion' => 'Río Quito'],
      ['codigo' => 'CO-CHO-27615', 'ubicacion' => 'Riosucio'],
      ['codigo' => 'CO-CHO-27660', 'ubicacion' => 'San José Del Palmar'],
      ['codigo' => 'CO-CHO-27745', 'ubicacion' => 'Sipí'],
      ['codigo' => 'CO-CHO-27787', 'ubicacion' => 'Tadó'],
      ['codigo' => 'CO-CHO-27800', 'ubicacion' => 'Unguía'],
      ['codigo' => 'CO-CHO-27810', 'ubicacion' => 'Unión Panamericana'],
      ['codigo' => 'CO-GUA', 'ubicacion' => 'Guainía'],
      ['codigo' => 'CO-GUA-94001', 'ubicacion' => 'Inírida'],
      ['codigo' => 'CO-GUA-94343', 'ubicacion' => 'Barranco Minas'],
      ['codigo' => 'CO-GUA-94663', 'ubicacion' => 'Mapiripana'],
      ['codigo' => 'CO-GUA-94883', 'ubicacion' => 'San Felipe'],
      ['codigo' => 'CO-GUA-94884', 'ubicacion' => 'Puerto Colombia'],
      ['codigo' => 'CO-GUA-94885', 'ubicacion' => 'La Guadalupe'],
      ['codigo' => 'CO-GUA-94886', 'ubicacion' => 'Cacahual'],
      ['codigo' => 'CO-GUA-94887', 'ubicacion' => 'Pana Pana'],
      ['codigo' => 'CO-GUA-94888', 'ubicacion' => 'Morichal'],
      ['codigo' => 'CO-GUV', 'ubicacion' => 'Guaviare'],
      ['codigo' => 'CO-GUV-95001', 'ubicacion' => 'San José Del Guaviare'],
      ['codigo' => 'CO-GUV-95015', 'ubicacion' => 'Calamar'],
      ['codigo' => 'CO-GUV-95025', 'ubicacion' => 'El Retorno'],
      ['codigo' => 'CO-GUV-95200', 'ubicacion' => 'Miraflores'],
      ['codigo' => 'CO-HUI', 'ubicacion' => 'Huila'],
      ['codigo' => 'CO-HUI-41001', 'ubicacion' => 'Neiva'],
      ['codigo' => 'CO-HUI-41006', 'ubicacion' => 'Acevedo'],
      ['codigo' => 'CO-HUI-41013', 'ubicacion' => 'Agrado'],
      ['codigo' => 'CO-HUI-41016', 'ubicacion' => 'Aipe'],
      ['codigo' => 'CO-HUI-41020', 'ubicacion' => 'Algeciras'],
      ['codigo' => 'CO-HUI-41026', 'ubicacion' => 'Altamira'],
      ['codigo' => 'CO-HUI-41078', 'ubicacion' => 'Baraya'],
      ['codigo' => 'CO-HUI-41132', 'ubicacion' => 'Campoalegre'],
      ['codigo' => 'CO-HUI-41206', 'ubicacion' => 'Colombia'],
      ['codigo' => 'CO-HUI-41244', 'ubicacion' => 'Elías'],
      ['codigo' => 'CO-HUI-41298', 'ubicacion' => 'Garzón'],
      ['codigo' => 'CO-HUI-41306', 'ubicacion' => 'Gigante'],
      ['codigo' => 'CO-HUI-41319', 'ubicacion' => 'Guadalupe'],
      ['codigo' => 'CO-HUI-41349', 'ubicacion' => 'Hobo'],
      ['codigo' => 'CO-HUI-41357', 'ubicacion' => 'Iquira'],
      ['codigo' => 'CO-HUI-41359', 'ubicacion' => 'Isnos'],
      ['codigo' => 'CO-HUI-41378', 'ubicacion' => 'La Argentina'],
      ['codigo' => 'CO-HUI-41396', 'ubicacion' => 'La Plata'],
      ['codigo' => 'CO-HUI-41483', 'ubicacion' => 'Nátaga'],
      ['codigo' => 'CO-HUI-41503', 'ubicacion' => 'Oporapa'],
      ['codigo' => 'CO-HUI-41518', 'ubicacion' => 'Paicol'],
      ['codigo' => 'CO-HUI-41524', 'ubicacion' => 'Palermo'],
      ['codigo' => 'CO-HUI-41530', 'ubicacion' => 'Palestina'],
      ['codigo' => 'CO-HUI-41548', 'ubicacion' => 'Pital'],
      ['codigo' => 'CO-HUI-41551', 'ubicacion' => 'Pitalito'],
      ['codigo' => 'CO-HUI-41615', 'ubicacion' => 'Rivera'],
      ['codigo' => 'CO-HUI-41660', 'ubicacion' => 'Saladoblanco'],
      ['codigo' => 'CO-HUI-41668', 'ubicacion' => 'San Agustín'],
      ['codigo' => 'CO-HUI-41676', 'ubicacion' => 'Santa María'],
      ['codigo' => 'CO-HUI-41770', 'ubicacion' => 'Suaza'],
      ['codigo' => 'CO-HUI-41791', 'ubicacion' => 'Tarqui'],
      ['codigo' => 'CO-HUI-41797', 'ubicacion' => 'Tesalia'],
      ['codigo' => 'CO-HUI-41799', 'ubicacion' => 'Tello'],
      ['codigo' => 'CO-HUI-41801', 'ubicacion' => 'Teruel'],
      ['codigo' => 'CO-HUI-41807', 'ubicacion' => 'Timaná'],
      ['codigo' => 'CO-HUI-41872', 'ubicacion' => 'Villavieja'],
      ['codigo' => 'CO-HUI-41885', 'ubicacion' => 'Yaguará'],
      ['codigo' => 'CO-LAG', 'ubicacion' => 'La Guajira'],
      ['codigo' => 'CO-LAG-44001', 'ubicacion' => 'Riohacha'],
      ['codigo' => 'CO-LAG-44035', 'ubicacion' => 'Albania'],
      ['codigo' => 'CO-LAG-44078', 'ubicacion' => 'Barrancas'],
      ['codigo' => 'CO-LAG-44090', 'ubicacion' => 'Dibulla'],
      ['codigo' => 'CO-LAG-44098', 'ubicacion' => 'Distracción'],
      ['codigo' => 'CO-LAG-44110', 'ubicacion' => 'El Molino'],
      ['codigo' => 'CO-LAG-44279', 'ubicacion' => 'Fonseca'],
      ['codigo' => 'CO-LAG-44378', 'ubicacion' => 'Hatonuevo'],
      ['codigo' => 'CO-LAG-44420', 'ubicacion' => 'La Jagua Del Pilar'],
      ['codigo' => 'CO-LAG-44430', 'ubicacion' => 'Maicao'],
      ['codigo' => 'CO-LAG-44560', 'ubicacion' => 'Manaure'],
      ['codigo' => 'CO-LAG-44650', 'ubicacion' => 'San Juan Del Cesar'],
      ['codigo' => 'CO-LAG-44847', 'ubicacion' => 'Uribia'],
      ['codigo' => 'CO-LAG-44855', 'ubicacion' => 'Urumita'],
      ['codigo' => 'CO-LAG-44874', 'ubicacion' => 'Villanueva'],
      ['codigo' => 'CO-MAG', 'ubicacion' => 'Magdalena'],
      ['codigo' => 'CO-MAG-47001', 'ubicacion' => 'Santa Marta'],
      ['codigo' => 'CO-MAG-47030', 'ubicacion' => 'Algarrobo'],
      ['codigo' => 'CO-MAG-47053', 'ubicacion' => 'Aracataca'],
      ['codigo' => 'CO-MAG-47058', 'ubicacion' => 'Ariguaní'],
      ['codigo' => 'CO-MAG-47161', 'ubicacion' => 'Cerro San Antonio'],
      ['codigo' => 'CO-MAG-47170', 'ubicacion' => 'Chibolo'],
      ['codigo' => 'CO-MAG-47189', 'ubicacion' => 'Ciénaga'],
      ['codigo' => 'CO-MAG-47205', 'ubicacion' => 'Concordia'],
      ['codigo' => 'CO-MAG-47245', 'ubicacion' => 'El Banco'],
      ['codigo' => 'CO-MAG-47258', 'ubicacion' => 'El Piñon'],
      ['codigo' => 'CO-MAG-47268', 'ubicacion' => 'El Retén'],
      ['codigo' => 'CO-MAG-47288', 'ubicacion' => 'Fundación'],
      ['codigo' => 'CO-MAG-47318', 'ubicacion' => 'Guamal'],
      ['codigo' => 'CO-MAG-47460', 'ubicacion' => 'Nueva Granada'],
      ['codigo' => 'CO-MAG-47541', 'ubicacion' => 'Pedraza'],
      ['codigo' => 'CO-MAG-47545', 'ubicacion' => 'Pijiño Del Carmen'],
      ['codigo' => 'CO-MAG-47551', 'ubicacion' => 'Pivijay'],
      ['codigo' => 'CO-MAG-47555', 'ubicacion' => 'Plato'],
      ['codigo' => 'CO-MAG-47570', 'ubicacion' => 'Puebloviejo'],
      ['codigo' => 'CO-MAG-47605', 'ubicacion' => 'Remolino'],
      ['codigo' => 'CO-MAG-47660', 'ubicacion' => 'Sabanas De San Angel'],
      ['codigo' => 'CO-MAG-47675', 'ubicacion' => 'Salamina'],
      ['codigo' => 'CO-MAG-47692', 'ubicacion' => 'San Sebastián De Buenavista'],
      ['codigo' => 'CO-MAG-47703', 'ubicacion' => 'San Zenón'],
      ['codigo' => 'CO-MAG-47707', 'ubicacion' => 'Santa Ana'],
      ['codigo' => 'CO-MAG-47720', 'ubicacion' => 'Santa Bárbara De Pinto'],
      ['codigo' => 'CO-MAG-47745', 'ubicacion' => 'Sitionuevo'],
      ['codigo' => 'CO-MAG-47798', 'ubicacion' => 'Tenerife'],
      ['codigo' => 'CO-MAG-47960', 'ubicacion' => 'Zapayán'],
      ['codigo' => 'CO-MAG-47980', 'ubicacion' => 'Zona Bananera'],
      ['codigo' => 'CO-MET', 'ubicacion' => 'Meta'],
      ['codigo' => 'CO-MET-50001', 'ubicacion' => 'Villavicencio'],
      ['codigo' => 'CO-MET-50006', 'ubicacion' => 'Acacías'],
      ['codigo' => 'CO-MET-50110', 'ubicacion' => 'Barranca De Upía'],
      ['codigo' => 'CO-MET-50124', 'ubicacion' => 'Cabuyaro'],
      ['codigo' => 'CO-MET-50150', 'ubicacion' => 'Castilla La Nueva'],
      ['codigo' => 'CO-MET-50223', 'ubicacion' => 'Cubarral'],
      ['codigo' => 'CO-MET-50226', 'ubicacion' => 'Cumaral'],
      ['codigo' => 'CO-MET-50245', 'ubicacion' => 'El Calvario'],
      ['codigo' => 'CO-MET-50251', 'ubicacion' => 'El Castillo'],
      ['codigo' => 'CO-MET-50270', 'ubicacion' => 'El Dorado'],
      ['codigo' => 'CO-MET-50287', 'ubicacion' => 'Fuente De Oro'],
      ['codigo' => 'CO-MET-50313', 'ubicacion' => 'Granada'],
      ['codigo' => 'CO-MET-50318', 'ubicacion' => 'Guamal'],
      ['codigo' => 'CO-MET-50325', 'ubicacion' => 'Mapiripán'],
      ['codigo' => 'CO-MET-50330', 'ubicacion' => 'Mesetas'],
      ['codigo' => 'CO-MET-50350', 'ubicacion' => 'La Macarena'],
      ['codigo' => 'CO-MET-50370', 'ubicacion' => 'Uribe'],
      ['codigo' => 'CO-MET-50400', 'ubicacion' => 'Lejanías'],
      ['codigo' => 'CO-MET-50450', 'ubicacion' => 'Puerto Concordia'],
      ['codigo' => 'CO-MET-50568', 'ubicacion' => 'Puerto Gaitán'],
      ['codigo' => 'CO-MET-50573', 'ubicacion' => 'Puerto López'],
      ['codigo' => 'CO-MET-50577', 'ubicacion' => 'Puerto Lleras'],
      ['codigo' => 'CO-MET-50590', 'ubicacion' => 'Puerto Rico'],
      ['codigo' => 'CO-MET-50606', 'ubicacion' => 'Restrepo'],
      ['codigo' => 'CO-MET-50680', 'ubicacion' => 'San Carlos De Guaroa'],
      ['codigo' => 'CO-MET-50683', 'ubicacion' => 'San Juan De Arama'],
      ['codigo' => 'CO-MET-50686', 'ubicacion' => 'San Juanito'],
      ['codigo' => 'CO-MET-50689', 'ubicacion' => 'San Martín'],
      ['codigo' => 'CO-MET-50711', 'ubicacion' => 'Vistahermosa'],
      ['codigo' => 'CO-NAR', 'ubicacion' => 'Nariño'],
      ['codigo' => 'CO-NAR-52001', 'ubicacion' => 'Pasto'],
      ['codigo' => 'CO-NAR-52019', 'ubicacion' => 'Albán'],
      ['codigo' => 'CO-NAR-52022', 'ubicacion' => 'Aldana'],
      ['codigo' => 'CO-NAR-52036', 'ubicacion' => 'Ancuyá'],
      ['codigo' => 'CO-NAR-52051', 'ubicacion' => 'Arboleda'],
      ['codigo' => 'CO-NAR-52079', 'ubicacion' => 'Barbacoas'],
      ['codigo' => 'CO-NAR-52083', 'ubicacion' => 'Belén'],
      ['codigo' => 'CO-NAR-52110', 'ubicacion' => 'Buesaco'],
      ['codigo' => 'CO-NAR-52203', 'ubicacion' => 'Colón'],
      ['codigo' => 'CO-NAR-52207', 'ubicacion' => 'Consaca'],
      ['codigo' => 'CO-NAR-52210', 'ubicacion' => 'Contadero'],
      ['codigo' => 'CO-NAR-52215', 'ubicacion' => 'Córdoba'],
      ['codigo' => 'CO-NAR-52224', 'ubicacion' => 'Cuaspud'],
      ['codigo' => 'CO-NAR-52227', 'ubicacion' => 'Cumbal'],
      ['codigo' => 'CO-NAR-52233', 'ubicacion' => 'Cumbitara'],
      ['codigo' => 'CO-NAR-52240', 'ubicacion' => 'Chachagüí'],
      ['codigo' => 'CO-NAR-52250', 'ubicacion' => 'El Charco'],
      ['codigo' => 'CO-NAR-52254', 'ubicacion' => 'El Peñol'],
      ['codigo' => 'CO-NAR-52256', 'ubicacion' => 'El Rosario'],
      ['codigo' => 'CO-NAR-52258', 'ubicacion' => 'El Tablón De Gómez'],
      ['codigo' => 'CO-NAR-52260', 'ubicacion' => 'El Tambo'],
      ['codigo' => 'CO-NAR-52287', 'ubicacion' => 'Funes'],
      ['codigo' => 'CO-NAR-52317', 'ubicacion' => 'Guachucal'],
      ['codigo' => 'CO-NAR-52320', 'ubicacion' => 'Guaitarilla'],
      ['codigo' => 'CO-NAR-52323', 'ubicacion' => 'Gualmatán'],
      ['codigo' => 'CO-NAR-52352', 'ubicacion' => 'Iles'],
      ['codigo' => 'CO-NAR-52354', 'ubicacion' => 'Imués'],
      ['codigo' => 'CO-NAR-52356', 'ubicacion' => 'Ipiales'],
      ['codigo' => 'CO-NAR-52378', 'ubicacion' => 'La Cruz'],
      ['codigo' => 'CO-NAR-52381', 'ubicacion' => 'La Florida'],
      ['codigo' => 'CO-NAR-52385', 'ubicacion' => 'La Llanada'],
      ['codigo' => 'CO-NAR-52390', 'ubicacion' => 'La Tola'],
      ['codigo' => 'CO-NAR-52399', 'ubicacion' => 'La Unión'],
      ['codigo' => 'CO-NAR-52405', 'ubicacion' => 'Leiva'],
      ['codigo' => 'CO-NAR-52411', 'ubicacion' => 'Linares'],
      ['codigo' => 'CO-NAR-52418', 'ubicacion' => 'Los Andes'],
      ['codigo' => 'CO-NAR-52427', 'ubicacion' => 'Magüi'],
      ['codigo' => 'CO-NAR-52435', 'ubicacion' => 'Mallama'],
      ['codigo' => 'CO-NAR-52473', 'ubicacion' => 'Mosquera'],
      ['codigo' => 'CO-NAR-52480', 'ubicacion' => 'Nariño'],
      ['codigo' => 'CO-NAR-52490', 'ubicacion' => 'Olaya Herrera'],
      ['codigo' => 'CO-NAR-52506', 'ubicacion' => 'Ospina'],
      ['codigo' => 'CO-NAR-52520', 'ubicacion' => 'Francisco Pizarro'],
      ['codigo' => 'CO-NAR-52540', 'ubicacion' => 'Policarpa'],
      ['codigo' => 'CO-NAR-52560', 'ubicacion' => 'Potosí'],
      ['codigo' => 'CO-NAR-52565', 'ubicacion' => 'Providencia'],
      ['codigo' => 'CO-NAR-52573', 'ubicacion' => 'Puerres'],
      ['codigo' => 'CO-NAR-52585', 'ubicacion' => 'Pupiales'],
      ['codigo' => 'CO-NAR-52612', 'ubicacion' => 'Ricaurte'],
      ['codigo' => 'CO-NAR-52621', 'ubicacion' => 'Roberto Payán'],
      ['codigo' => 'CO-NAR-52678', 'ubicacion' => 'Samaniego'],
      ['codigo' => 'CO-NAR-52683', 'ubicacion' => 'Sandoná'],
      ['codigo' => 'CO-NAR-52685', 'ubicacion' => 'San Bernardo'],
      ['codigo' => 'CO-NAR-52687', 'ubicacion' => 'San Lorenzo'],
      ['codigo' => 'CO-NAR-52693', 'ubicacion' => 'San Pablo'],
      ['codigo' => 'CO-NAR-52694', 'ubicacion' => 'San Pedro De Cartago'],
      ['codigo' => 'CO-NAR-52696', 'ubicacion' => 'Santa Bárbara'],
      ['codigo' => 'CO-NAR-52699', 'ubicacion' => 'Santacruz'],
      ['codigo' => 'CO-NAR-52720', 'ubicacion' => 'Sapuyes'],
      ['codigo' => 'CO-NAR-52786', 'ubicacion' => 'Taminango'],
      ['codigo' => 'CO-NAR-52788', 'ubicacion' => 'Tangua'],
      ['codigo' => 'CO-NAR-52835', 'ubicacion' => 'Tumaco'],
      ['codigo' => 'CO-NAR-52838', 'ubicacion' => 'Túquerres'],
      ['codigo' => 'CO-NAR-52885', 'ubicacion' => 'Yacuanquer'],
      ['codigo' => 'CO-NSA', 'ubicacion' => 'Norte de Santander'],
      ['codigo' => 'CO-NSA-54001', 'ubicacion' => 'Cúcuta'],
      ['codigo' => 'CO-NSA-54003', 'ubicacion' => 'Abrego'],
      ['codigo' => 'CO-NSA-54051', 'ubicacion' => 'Arboledas'],
      ['codigo' => 'CO-NSA-54099', 'ubicacion' => 'Bochalema'],
      ['codigo' => 'CO-NSA-54109', 'ubicacion' => 'Bucarasica'],
      ['codigo' => 'CO-NSA-54125', 'ubicacion' => 'Cácota'],
      ['codigo' => 'CO-NSA-54128', 'ubicacion' => 'Cachirá'],
      ['codigo' => 'CO-NSA-54172', 'ubicacion' => 'Chinácota'],
      ['codigo' => 'CO-NSA-54174', 'ubicacion' => 'Chitagá'],
      ['codigo' => 'CO-NSA-54206', 'ubicacion' => 'Convención'],
      ['codigo' => 'CO-NSA-54223', 'ubicacion' => 'Cucutilla'],
      ['codigo' => 'CO-NSA-54239', 'ubicacion' => 'Durania'],
      ['codigo' => 'CO-NSA-54245', 'ubicacion' => 'El Carmen'],
      ['codigo' => 'CO-NSA-54250', 'ubicacion' => 'El Tarra'],
      ['codigo' => 'CO-NSA-54261', 'ubicacion' => 'El Zulia'],
      ['codigo' => 'CO-NSA-54313', 'ubicacion' => 'Gramalote'],
      ['codigo' => 'CO-NSA-54344', 'ubicacion' => 'Hacarí'],
      ['codigo' => 'CO-NSA-54347', 'ubicacion' => 'Herrán'],
      ['codigo' => 'CO-NSA-54377', 'ubicacion' => 'Labateca'],
      ['codigo' => 'CO-NSA-54385', 'ubicacion' => 'La Esperanza'],
      ['codigo' => 'CO-NSA-54398', 'ubicacion' => 'La Playa'],
      ['codigo' => 'CO-NSA-54405', 'ubicacion' => 'Los Patios'],
      ['codigo' => 'CO-NSA-54418', 'ubicacion' => 'Lourdes'],
      ['codigo' => 'CO-NSA-54480', 'ubicacion' => 'Mutiscua'],
      ['codigo' => 'CO-NSA-54498', 'ubicacion' => 'Ocaña'],
      ['codigo' => 'CO-NSA-54518', 'ubicacion' => 'Pamplona'],
      ['codigo' => 'CO-NSA-54520', 'ubicacion' => 'Pamplonita'],
      ['codigo' => 'CO-NSA-54553', 'ubicacion' => 'Puerto Santander'],
      ['codigo' => 'CO-NSA-54599', 'ubicacion' => 'Ragonvalia'],
      ['codigo' => 'CO-NSA-54660', 'ubicacion' => 'Salazar'],
      ['codigo' => 'CO-NSA-54670', 'ubicacion' => 'San Calixto'],
      ['codigo' => 'CO-NSA-54673', 'ubicacion' => 'San Cayetano'],
      ['codigo' => 'CO-NSA-54680', 'ubicacion' => 'Santiago'],
      ['codigo' => 'CO-NSA-54720', 'ubicacion' => 'Sardinata'],
      ['codigo' => 'CO-NSA-54743', 'ubicacion' => 'Silos'],
      ['codigo' => 'CO-NSA-54800', 'ubicacion' => 'Teorama'],
      ['codigo' => 'CO-NSA-54810', 'ubicacion' => 'Tibú'],
      ['codigo' => 'CO-NSA-54820', 'ubicacion' => 'Toledo'],
      ['codigo' => 'CO-NSA-54871', 'ubicacion' => 'Villa Caro'],
      ['codigo' => 'CO-NSA-54874', 'ubicacion' => 'Villa Del Rosario'],
      ['codigo' => 'CO-PUT', 'ubicacion' => 'Putumayo'],
      ['codigo' => 'CO-PUT-86001', 'ubicacion' => 'Mocoa'],
      ['codigo' => 'CO-PUT-86219', 'ubicacion' => 'Colón'],
      ['codigo' => 'CO-PUT-86320', 'ubicacion' => 'Orito'],
      ['codigo' => 'CO-PUT-86568', 'ubicacion' => 'Puerto Asís'],
      ['codigo' => 'CO-PUT-86569', 'ubicacion' => 'Puerto Caicedo'],
      ['codigo' => 'CO-PUT-86571', 'ubicacion' => 'Puerto Guzmán'],
      ['codigo' => 'CO-PUT-86573', 'ubicacion' => 'Leguízamo'],
      ['codigo' => 'CO-PUT-86749', 'ubicacion' => 'Sibundoy'],
      ['codigo' => 'CO-PUT-86755', 'ubicacion' => 'San Francisco'],
      ['codigo' => 'CO-PUT-86757', 'ubicacion' => 'San Miguel'],
      ['codigo' => 'CO-PUT-86760', 'ubicacion' => 'Santiago'],
      ['codigo' => 'CO-PUT-86865', 'ubicacion' => 'Valle Del Guamuez'],
      ['codigo' => 'CO-PUT-86885', 'ubicacion' => 'Villagarzón'],
      ['codigo' => 'CO-QUI', 'ubicacion' => 'Quindío'],
      ['codigo' => 'CO-QUI-63001', 'ubicacion' => 'Armenia'],
      ['codigo' => 'CO-QUI-63111', 'ubicacion' => 'Buenavista'],
      ['codigo' => 'CO-QUI-63130', 'ubicacion' => 'Calarca'],
      ['codigo' => 'CO-QUI-63190', 'ubicacion' => 'Circasia'],
      ['codigo' => 'CO-QUI-63212', 'ubicacion' => 'Córdoba'],
      ['codigo' => 'CO-QUI-63272', 'ubicacion' => 'Filandia'],
      ['codigo' => 'CO-QUI-63302', 'ubicacion' => 'Génova'],
      ['codigo' => 'CO-QUI-63401', 'ubicacion' => 'La Tebaida'],
      ['codigo' => 'CO-QUI-63470', 'ubicacion' => 'Montenegro'],
      ['codigo' => 'CO-QUI-63548', 'ubicacion' => 'Pijao'],
      ['codigo' => 'CO-QUI-63594', 'ubicacion' => 'Quimbaya'],
      ['codigo' => 'CO-QUI-63690', 'ubicacion' => 'Salento'],
      ['codigo' => 'CO-RIS', 'ubicacion' => 'Risaralda'],
      ['codigo' => 'CO-RIS-66001', 'ubicacion' => 'Pereira'],
      ['codigo' => 'CO-RIS-66045', 'ubicacion' => 'Apía'],
      ['codigo' => 'CO-RIS-66075', 'ubicacion' => 'Balboa'],
      ['codigo' => 'CO-RIS-66088', 'ubicacion' => 'Belén De Umbría'],
      ['codigo' => 'CO-RIS-66170', 'ubicacion' => 'Dosquebradas'],
      ['codigo' => 'CO-RIS-66318', 'ubicacion' => 'Guática'],
      ['codigo' => 'CO-RIS-66383', 'ubicacion' => 'La Celia'],
      ['codigo' => 'CO-RIS-66400', 'ubicacion' => 'La Virginia'],
      ['codigo' => 'CO-RIS-66440', 'ubicacion' => 'Marsella'],
      ['codigo' => 'CO-RIS-66456', 'ubicacion' => 'Mistrató'],
      ['codigo' => 'CO-RIS-66572', 'ubicacion' => 'Pueblo Rico'],
      ['codigo' => 'CO-RIS-66594', 'ubicacion' => 'Quinchía'],
      ['codigo' => 'CO-RIS-66682', 'ubicacion' => 'Santa Rosa De Cabal'],
      ['codigo' => 'CO-RIS-66687', 'ubicacion' => 'Santuario'],
      ['codigo' => 'CO-SAP', 'ubicacion' => 'San Andrés, Providencia y Santa Catalina'],
      ['codigo' => 'CO-SAP-88001', 'ubicacion' => 'San Andrés'],
      ['codigo' => 'CO-SAP-88564', 'ubicacion' => 'Providencia'],
      ['codigo' => 'CO-SAN', 'ubicacion' => 'Santander'],
      ['codigo' => 'CO-SAN-68001', 'ubicacion' => 'Bucaramanga'],
      ['codigo' => 'CO-SAN-68013', 'ubicacion' => 'Aguada'],
      ['codigo' => 'CO-SAN-68020', 'ubicacion' => 'Albania'],
      ['codigo' => 'CO-SAN-68051', 'ubicacion' => 'Aratoca'],
      ['codigo' => 'CO-SAN-68077', 'ubicacion' => 'Barbosa'],
      ['codigo' => 'CO-SAN-68079', 'ubicacion' => 'Barichara'],
      ['codigo' => 'CO-SAN-68081', 'ubicacion' => 'Barrancabermeja'],
      ['codigo' => 'CO-SAN-68092', 'ubicacion' => 'Betulia'],
      ['codigo' => 'CO-SAN-68101', 'ubicacion' => 'Bolívar'],
      ['codigo' => 'CO-SAN-68121', 'ubicacion' => 'Cabrera'],
      ['codigo' => 'CO-SAN-68132', 'ubicacion' => 'California'],
      ['codigo' => 'CO-SAN-68147', 'ubicacion' => 'Capitanejo'],
      ['codigo' => 'CO-SAN-68152', 'ubicacion' => 'Carcasí'],
      ['codigo' => 'CO-SAN-68160', 'ubicacion' => 'Cepitá'],
      ['codigo' => 'CO-SAN-68162', 'ubicacion' => 'Cerrito'],
      ['codigo' => 'CO-SAN-68167', 'ubicacion' => 'Charalá'],
      ['codigo' => 'CO-SAN-68169', 'ubicacion' => 'Charta'],
      ['codigo' => 'CO-SAN-68176', 'ubicacion' => 'Chima'],
      ['codigo' => 'CO-SAN-68179', 'ubicacion' => 'Chipatá'],
      ['codigo' => 'CO-SAN-68190', 'ubicacion' => 'Cimitarra'],
      ['codigo' => 'CO-SAN-68207', 'ubicacion' => 'Concepción'],
      ['codigo' => 'CO-SAN-68209', 'ubicacion' => 'Confines'],
      ['codigo' => 'CO-SAN-68211', 'ubicacion' => 'Contratación'],
      ['codigo' => 'CO-SAN-68217', 'ubicacion' => 'Coromoro'],
      ['codigo' => 'CO-SAN-68229', 'ubicacion' => 'Curití'],
      ['codigo' => 'CO-SAN-68235', 'ubicacion' => 'El Carmen De Chucurí'],
      ['codigo' => 'CO-SAN-68245', 'ubicacion' => 'El Guacamayo'],
      ['codigo' => 'CO-SAN-68250', 'ubicacion' => 'El Peñón'],
      ['codigo' => 'CO-SAN-68255', 'ubicacion' => 'El Playón'],
      ['codigo' => 'CO-SAN-68264', 'ubicacion' => 'Encino'],
      ['codigo' => 'CO-SAN-68266', 'ubicacion' => 'Enciso'],
      ['codigo' => 'CO-SAN-68271', 'ubicacion' => 'Florián'],
      ['codigo' => 'CO-SAN-68276', 'ubicacion' => 'Floridablanca'],
      ['codigo' => 'CO-SAN-68296', 'ubicacion' => 'Galán'],
      ['codigo' => 'CO-SAN-68298', 'ubicacion' => 'Gambita'],
      ['codigo' => 'CO-SAN-68307', 'ubicacion' => 'Girón'],
      ['codigo' => 'CO-SAN-68318', 'ubicacion' => 'Guaca'],
      ['codigo' => 'CO-SAN-68320', 'ubicacion' => 'Guadalupe'],
      ['codigo' => 'CO-SAN-68322', 'ubicacion' => 'Guapotá'],
      ['codigo' => 'CO-SAN-68324', 'ubicacion' => 'Guavatá'],
      ['codigo' => 'CO-SAN-68327', 'ubicacion' => 'Güepsa'],
      ['codigo' => 'CO-SAN-68344', 'ubicacion' => 'Hato'],
      ['codigo' => 'CO-SAN-68368', 'ubicacion' => 'Jesús María'],
      ['codigo' => 'CO-SAN-68370', 'ubicacion' => 'Jordán'],
      ['codigo' => 'CO-SAN-68377', 'ubicacion' => 'La Belleza'],
      ['codigo' => 'CO-SAN-68385', 'ubicacion' => 'Landázuri'],
      ['codigo' => 'CO-SAN-68397', 'ubicacion' => 'La Paz'],
      ['codigo' => 'CO-SAN-68406', 'ubicacion' => 'Lebríja'],
      ['codigo' => 'CO-SAN-68418', 'ubicacion' => 'Los Santos'],
      ['codigo' => 'CO-SAN-68425', 'ubicacion' => 'Macaravita'],
      ['codigo' => 'CO-SAN-68432', 'ubicacion' => 'Málaga'],
      ['codigo' => 'CO-SAN-68444', 'ubicacion' => 'Matanza'],
      ['codigo' => 'CO-SAN-68464', 'ubicacion' => 'Mogotes'],
      ['codigo' => 'CO-SAN-68468', 'ubicacion' => 'Molagavita'],
      ['codigo' => 'CO-SAN-68498', 'ubicacion' => 'Ocamonte'],
      ['codigo' => 'CO-SAN-68500', 'ubicacion' => 'Oiba'],
      ['codigo' => 'CO-SAN-68502', 'ubicacion' => 'Onzaga'],
      ['codigo' => 'CO-SAN-68522', 'ubicacion' => 'Palmar'],
      ['codigo' => 'CO-SAN-68524', 'ubicacion' => 'Palmas Del Socorro'],
      ['codigo' => 'CO-SAN-68533', 'ubicacion' => 'Páramo'],
      ['codigo' => 'CO-SAN-68547', 'ubicacion' => 'Piedecuesta'],
      ['codigo' => 'CO-SAN-68549', 'ubicacion' => 'Pinchote'],
      ['codigo' => 'CO-SAN-68572', 'ubicacion' => 'Puente Nacional'],
      ['codigo' => 'CO-SAN-68573', 'ubicacion' => 'Puerto Parra'],
      ['codigo' => 'CO-SAN-68575', 'ubicacion' => 'Puerto Wilches'],
      ['codigo' => 'CO-SAN-68615', 'ubicacion' => 'Rionegro'],
      ['codigo' => 'CO-SAN-68655', 'ubicacion' => 'Sabana De Torres'],
      ['codigo' => 'CO-SAN-68669', 'ubicacion' => 'San Andrés'],
      ['codigo' => 'CO-SAN-68673', 'ubicacion' => 'San Benito'],
      ['codigo' => 'CO-SAN-68679', 'ubicacion' => 'San Gil'],
      ['codigo' => 'CO-SAN-68682', 'ubicacion' => 'San Joaquín'],
      ['codigo' => 'CO-SAN-68684', 'ubicacion' => 'San José De Miranda'],
      ['codigo' => 'CO-SAN-68686', 'ubicacion' => 'San Miguel'],
      ['codigo' => 'CO-SAN-68689', 'ubicacion' => 'San Vicente De Chucurí'],
      ['codigo' => 'CO-SAN-68705', 'ubicacion' => 'Santa Bárbara'],
      ['codigo' => 'CO-SAN-68720', 'ubicacion' => 'Santa Helena Del Opón'],
      ['codigo' => 'CO-SAN-68745', 'ubicacion' => 'Simacota'],
      ['codigo' => 'CO-SAN-68755', 'ubicacion' => 'Socorro'],
      ['codigo' => 'CO-SAN-68770', 'ubicacion' => 'Suaita'],
      ['codigo' => 'CO-SAN-68773', 'ubicacion' => 'Sucre'],
      ['codigo' => 'CO-SAN-68780', 'ubicacion' => 'Suratá'],
      ['codigo' => 'CO-SAN-68820', 'ubicacion' => 'Tona'],
      ['codigo' => 'CO-SAN-68855', 'ubicacion' => 'Valle De San José'],
      ['codigo' => 'CO-SAN-68861', 'ubicacion' => 'Vélez'],
      ['codigo' => 'CO-SAN-68867', 'ubicacion' => 'Vetas'],
      ['codigo' => 'CO-SAN-68872', 'ubicacion' => 'Villanueva'],
      ['codigo' => 'CO-SAN-68895', 'ubicacion' => 'Zapatoca'],
      ['codigo' => 'CO-SUC', 'ubicacion' => 'Sucre'],
      ['codigo' => 'CO-SUC-70001', 'ubicacion' => 'Sincelejo'],
      ['codigo' => 'CO-SUC-70110', 'ubicacion' => 'Buenavista'],
      ['codigo' => 'CO-SUC-70124', 'ubicacion' => 'Caimito'],
      ['codigo' => 'CO-SUC-70204', 'ubicacion' => 'Coloso'],
      ['codigo' => 'CO-SUC-70215', 'ubicacion' => 'Corozal'],
      ['codigo' => 'CO-SUC-70221', 'ubicacion' => 'Coveñas'],
      ['codigo' => 'CO-SUC-70230', 'ubicacion' => 'Chalán'],
      ['codigo' => 'CO-SUC-70233', 'ubicacion' => 'El Roble'],
      ['codigo' => 'CO-SUC-70235', 'ubicacion' => 'Galeras'],
      ['codigo' => 'CO-SUC-70265', 'ubicacion' => 'Guaranda'],
      ['codigo' => 'CO-SUC-70400', 'ubicacion' => 'La Unión'],
      ['codigo' => 'CO-SUC-70418', 'ubicacion' => 'Los Palmitos'],
      ['codigo' => 'CO-SUC-70429', 'ubicacion' => 'Majagual'],
      ['codigo' => 'CO-SUC-70473', 'ubicacion' => 'Morroa'],
      ['codigo' => 'CO-SUC-70508', 'ubicacion' => 'Ovejas'],
      ['codigo' => 'CO-SUC-70523', 'ubicacion' => 'Palmito'],
      ['codigo' => 'CO-SUC-70670', 'ubicacion' => 'Sampués'],
      ['codigo' => 'CO-SUC-70678', 'ubicacion' => 'San Benito Abad'],
      ['codigo' => 'CO-SUC-70702', 'ubicacion' => 'San Juan De Betulia'],
      ['codigo' => 'CO-SUC-70708', 'ubicacion' => 'San Marcos'],
      ['codigo' => 'CO-SUC-70713', 'ubicacion' => 'San Onofre'],
      ['codigo' => 'CO-SUC-70717', 'ubicacion' => 'San Pedro'],
      ['codigo' => 'CO-SUC-70742', 'ubicacion' => 'Sincé'],
      ['codigo' => 'CO-SUC-70771', 'ubicacion' => 'Sucre'],
      ['codigo' => 'CO-SUC-70820', 'ubicacion' => 'Santiago De Tolú'],
      ['codigo' => 'CO-SUC-70823', 'ubicacion' => 'Tolú Viejo'],
      ['codigo' => 'CO-TOL', 'ubicacion' => 'Tolima'],
      ['codigo' => 'CO-TOL-73001', 'ubicacion' => 'Ibagué'],
      ['codigo' => 'CO-TOL-73024', 'ubicacion' => 'Alpujarra'],
      ['codigo' => 'CO-TOL-73026', 'ubicacion' => 'Alvarado'],
      ['codigo' => 'CO-TOL-73030', 'ubicacion' => 'Ambalema'],
      ['codigo' => 'CO-TOL-73043', 'ubicacion' => 'Anzoátegui'],
      ['codigo' => 'CO-TOL-73055', 'ubicacion' => 'Armero'],
      ['codigo' => 'CO-TOL-73067', 'ubicacion' => 'Ataco'],
      ['codigo' => 'CO-TOL-73124', 'ubicacion' => 'Cajamarca'],
      ['codigo' => 'CO-TOL-73148', 'ubicacion' => 'Carmen De Apicalá'],
      ['codigo' => 'CO-TOL-73152', 'ubicacion' => 'Casabianca'],
      ['codigo' => 'CO-TOL-73168', 'ubicacion' => 'Chaparral'],
      ['codigo' => 'CO-TOL-73200', 'ubicacion' => 'Coello'],
      ['codigo' => 'CO-TOL-73217', 'ubicacion' => 'Coyaima'],
      ['codigo' => 'CO-TOL-73226', 'ubicacion' => 'Cunday'],
      ['codigo' => 'CO-TOL-73236', 'ubicacion' => 'Dolores'],
      ['codigo' => 'CO-TOL-73268', 'ubicacion' => 'Espinal'],
      ['codigo' => 'CO-TOL-73270', 'ubicacion' => 'Falan'],
      ['codigo' => 'CO-TOL-73275', 'ubicacion' => 'Flandes'],
      ['codigo' => 'CO-TOL-73283', 'ubicacion' => 'Fresno'],
      ['codigo' => 'CO-TOL-73319', 'ubicacion' => 'Guamo'],
      ['codigo' => 'CO-TOL-73347', 'ubicacion' => 'Herveo'],
      ['codigo' => 'CO-TOL-73349', 'ubicacion' => 'Honda'],
      ['codigo' => 'CO-TOL-73352', 'ubicacion' => 'Icononzo'],
      ['codigo' => 'CO-TOL-73408', 'ubicacion' => 'Lérida'],
      ['codigo' => 'CO-TOL-73411', 'ubicacion' => 'Líbano'],
      ['codigo' => 'CO-TOL-73443', 'ubicacion' => 'Mariquita'],
      ['codigo' => 'CO-TOL-73449', 'ubicacion' => 'Melgar'],
      ['codigo' => 'CO-TOL-73461', 'ubicacion' => 'Murillo'],
      ['codigo' => 'CO-TOL-73483', 'ubicacion' => 'Natagaima'],
      ['codigo' => 'CO-TOL-73504', 'ubicacion' => 'Ortega'],
      ['codigo' => 'CO-TOL-73520', 'ubicacion' => 'Palocabildo'],
      ['codigo' => 'CO-TOL-73547', 'ubicacion' => 'Piedras'],
      ['codigo' => 'CO-TOL-73555', 'ubicacion' => 'Planadas'],
      ['codigo' => 'CO-TOL-73563', 'ubicacion' => 'Prado'],
      ['codigo' => 'CO-TOL-73585', 'ubicacion' => 'Purificación'],
      ['codigo' => 'CO-TOL-73616', 'ubicacion' => 'Rioblanco'],
      ['codigo' => 'CO-TOL-73622', 'ubicacion' => 'Roncesvalles'],
      ['codigo' => 'CO-TOL-73624', 'ubicacion' => 'Rovira'],
      ['codigo' => 'CO-TOL-73671', 'ubicacion' => 'Saldaña'],
      ['codigo' => 'CO-TOL-73675', 'ubicacion' => 'San Antonio'],
      ['codigo' => 'CO-TOL-73678', 'ubicacion' => 'San Luis'],
      ['codigo' => 'CO-TOL-73686', 'ubicacion' => 'Santa Isabel'],
      ['codigo' => 'CO-TOL-73770', 'ubicacion' => 'Suárez'],
      ['codigo' => 'CO-TOL-73854', 'ubicacion' => 'Valle De San Juan'],
      ['codigo' => 'CO-TOL-73861', 'ubicacion' => 'Venadillo'],
      ['codigo' => 'CO-TOL-73870', 'ubicacion' => 'Villahermosa'],
      ['codigo' => 'CO-TOL-73873', 'ubicacion' => 'Villarrica'],
      ['codigo' => 'CO-VAC', 'ubicacion' => 'Valle del Cauca'],
      ['codigo' => 'CO-VAC-76001', 'ubicacion' => 'Cali'],
      ['codigo' => 'CO-VAC-76020', 'ubicacion' => 'Alcalá'],
      ['codigo' => 'CO-VAC-76036', 'ubicacion' => 'Andalucía'],
      ['codigo' => 'CO-VAC-76041', 'ubicacion' => 'Ansermanuevo'],
      ['codigo' => 'CO-VAC-76054', 'ubicacion' => 'Argelia'],
      ['codigo' => 'CO-VAC-76100', 'ubicacion' => 'Bolívar'],
      ['codigo' => 'CO-VAC-76109', 'ubicacion' => 'Buenaventura'],
      ['codigo' => 'CO-VAC-76111', 'ubicacion' => 'Guadalajara De Buga'],
      ['codigo' => 'CO-VAC-76113', 'ubicacion' => 'Bugalagrande'],
      ['codigo' => 'CO-VAC-76122', 'ubicacion' => 'Caicedonia'],
      ['codigo' => 'CO-VAC-76126', 'ubicacion' => 'Calima'],
      ['codigo' => 'CO-VAC-76130', 'ubicacion' => 'Candelaria'],
      ['codigo' => 'CO-VAC-76147', 'ubicacion' => 'Cartago'],
      ['codigo' => 'CO-VAC-76233', 'ubicacion' => 'Dagua'],
      ['codigo' => 'CO-VAC-76243', 'ubicacion' => 'El Águila'],
      ['codigo' => 'CO-VAC-76246', 'ubicacion' => 'El Cairo'],
      ['codigo' => 'CO-VAC-76248', 'ubicacion' => 'El Cerrito'],
      ['codigo' => 'CO-VAC-76250', 'ubicacion' => 'El Dovio'],
      ['codigo' => 'CO-VAC-76275', 'ubicacion' => 'Florida'],
      ['codigo' => 'CO-VAC-76306', 'ubicacion' => 'Ginebra'],
      ['codigo' => 'CO-VAC-76318', 'ubicacion' => 'Guacarí'],
      ['codigo' => 'CO-VAC-76364', 'ubicacion' => 'Jamundí'],
      ['codigo' => 'CO-VAC-76377', 'ubicacion' => 'La Cumbre'],
      ['codigo' => 'CO-VAC-76400', 'ubicacion' => 'La Unión'],
      ['codigo' => 'CO-VAC-76403', 'ubicacion' => 'La Victoria'],
      ['codigo' => 'CO-VAC-76497', 'ubicacion' => 'Obando'],
      ['codigo' => 'CO-VAC-76520', 'ubicacion' => 'Palmira'],
      ['codigo' => 'CO-VAC-76563', 'ubicacion' => 'Pradera'],
      ['codigo' => 'CO-VAC-76606', 'ubicacion' => 'Restrepo'],
      ['codigo' => 'CO-VAC-76616', 'ubicacion' => 'Riofrío'],
      ['codigo' => 'CO-VAC-76622', 'ubicacion' => 'Roldanillo'],
      ['codigo' => 'CO-VAC-76670', 'ubicacion' => 'San Pedro'],
      ['codigo' => 'CO-VAC-76736', 'ubicacion' => 'Sevilla'],
      ['codigo' => 'CO-VAC-76823', 'ubicacion' => 'Toro'],
      ['codigo' => 'CO-VAC-76828', 'ubicacion' => 'Trujillo'],
      ['codigo' => 'CO-VAC-76834', 'ubicacion' => 'Tuluá'],
      ['codigo' => 'CO-VAC-76845', 'ubicacion' => 'Ulloa'],
      ['codigo' => 'CO-VAC-76863', 'ubicacion' => 'Versalles'],
      ['codigo' => 'CO-VAC-76869', 'ubicacion' => 'Vijes'],
      ['codigo' => 'CO-VAC-76890', 'ubicacion' => 'Yotoco'],
      ['codigo' => 'CO-VAC-76892', 'ubicacion' => 'Yumbo'],
      ['codigo' => 'CO-VAC-76895', 'ubicacion' => 'Zarzal'],
      ['codigo' => 'CO-VAU', 'ubicacion' => 'Vaupés'],
      ['codigo' => 'CO-VAU-97001', 'ubicacion' => 'Mitú'],
      ['codigo' => 'CO-VAU-97161', 'ubicacion' => 'Caruru'],
      ['codigo' => 'CO-VAU-97511', 'ubicacion' => 'Pacoa'],
      ['codigo' => 'CO-VAU-97666', 'ubicacion' => 'Taraira'],
      ['codigo' => 'CO-VAU-97777', 'ubicacion' => 'Papunaua'],
      ['codigo' => 'CO-VAU-97889', 'ubicacion' => 'Yavaraté'],
      ['codigo' => 'CO-VID', 'ubicacion' => 'Vichada'],
      ['codigo' => 'CO-VID-99001', 'ubicacion' => 'Puerto Carreño'],
      ['codigo' => 'CO-VID-99524', 'ubicacion' => 'La Primavera'],
      ['codigo' => 'CO-VID-99624', 'ubicacion' => 'Santa Rosalía'],
      ['codigo' => 'CO-VID-99773', 'ubicacion' => 'Cumaribo'],

    ];

    DB::table('Sgc_ubicaciones')->insert($ubicacion);
  }
}
